import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Amore Pacific",
  slug: "amore-pacific",
  officialUrl: "https://www.apgroup.com/",
  domain: "apgroup.com",
  seoTitle: "AmorePacific: Gigante Coreana de K-Beauty | Top 12 Mundial 2026",
  seoDescription:
    "AmorePacific é a maior empresa de cosméticos da Coreia do Sul, dona de Sulwhasoo, Laneige, Innisfree e mais. US$ 3,5 bi em receita, presença em 50+ países. K-Beauty premium mundial.",
  rankingLabel: "TOP 12 MUNDIAL • FORBES GLOBAL 2000 2026",
  heroHeadlineSuffix: "A Gigante Coreana da K-Beauty",
  heroParagraph:
    "Fundada em 1945 em Seul por Suh Sung-Whan (a partir dos óleos de camélia da mãe), a AmorePacific é a maior empresa de cosméticos da Coreia do Sul — dona de Sulwhasoo, Laneige, Innisfree, Etude House e mais de 30 marcas — com US$ 3,5 bi em receita anual.",
  heroBadges: [
    { label: "80+ anos", icon: "calendar" },
    { label: "50+ países", icon: "globe" },
    { label: "30+ marcas", icon: "check" },
    { label: "K-Beauty líder", icon: "check" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 12", hint: "DSN Global 100 + Forbes Global 2000" },
    { icon: "calendar", label: "Fundação", value: "1945", hint: "Como Pacific Chemical Industrial Corp." },
    { icon: "map", label: "País de Origem", value: "Coreia do Sul 🇰🇷", hint: "Sede em Yongsan, Seul" },
    { icon: "globe", label: "Países", value: "50+", hint: "Ásia, Américas, Europa, Oriente Médio" },
    { icon: "users", label: "Beauty Counselors", value: "3 milhões+", hint: "Rede global (direct selling + retail)" },
    { icon: "package", label: "Marcas", value: "30+", hint: "Sulwhasoo, Laneige, Innisfree, Etude, Mamonde, Ryo" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 3,5 bilhões", hint: "Grupo AmorePacific consolidado" },
    { icon: "factory", label: "R&D", value: "Yongin", hint: "Instituto de Beleza mais avançado da Ásia" },
  ],
  aboutHtml: `
    <p>A <strong>AmorePacific Corporation</strong> (아모레퍼시픽) é a maior empresa de cosméticos da Coreia do Sul, fundada em <strong>1945</strong> por <em>Suh Sung-Whan</em> em Seul. Sua origem remonta a 1932, quando a mãe de Sung-Whan, Yun Dok-Jeong, começou a produzir óleo de camélia — dando origem à empresa Pacific Chemical Industrial Corp. em 1945.</p>
    <p>É a <strong>maior potência mundial de K-Beauty</strong>, dona de mais de <strong>30 marcas globais</strong>: <strong>Sulwhasoo</strong> (herbal luxo), <strong>Laneige</strong> (hidratação), <strong>Innisfree</strong> (natural de Jeju), <strong>Etude House</strong> (jovem), <strong>Mamonde</strong> (floral), <strong>Ryo</strong> (capilar), <strong>Iope</strong> (bio-ciência), <strong>HERA</strong> (moderno), <strong>Primera</strong> (orgânico), entre outras.</p>
    <p>Com <strong>US$ 3,5 bi em receita anual</strong>, a AmorePacific é <strong>Top 12 mundial</strong>, opera em <strong>50+ países</strong> e conta com o <strong>maior instituto de pesquisa em beleza da Ásia</strong> em Yongin (mais de 500 cientistas). Opera modelo híbrido: venda direta (Beauty Counselors, Aritaum), varejo próprio, e-commerce e retail internacional (Sephora, Amazon, Ulta).</p>
    <p>Em 2026, AmorePacific segue como <strong>referência global em innovation cosmético</strong> — pioneira em cushion foundation (2008), sheet masks premium e formulações com ginseng e chá verde de Jeju.</p>
  `,
  timelineTitle: "Do óleo de camélia ao império K-Beauty mundial",
  milestones: [
    { year: "1932", title: "Origem familiar", text: "Yun Dok-Jeong começa a vender óleo de camélia em Kaesong." },
    { year: "1945", title: "Fundação oficial", text: "Suh Sung-Whan funda Pacific Chemical Industrial Corp." },
    { year: "1964", title: "Beauty Counselors", text: "Introduz o pioneiro sistema coreano de venda direta." },
    { year: "1990", title: "Renomeada", text: "Passa a se chamar AmorePacific — foco internacional." },
    { year: "2000", title: "Explosão da K-Beauty", text: "Lidera o boom global de cosméticos coreanos." },
    { year: "2008", title: "Cushion Foundation", text: "Iope lança o cushion — inovação copiada mundialmente." },
    { year: "2016", title: "US$ 6 bi de pico", text: "Recorde histórico impulsionado pela China." },
    { year: "2020", title: "Reestruturação", text: "Foca em digital, EUA e Europa após crise chinesa." },
    { year: "2024", title: "Tira-teima nos EUA", text: "Compra minoritária Rare Beauty (Selena Gomez — parceria)." },
    { year: "2026", title: "Top 12 mundial", text: "US$ 3,5 bi consolidados — líder K-Beauty global." },
  ],
  productsIntro:
    "Portfólio de <strong>30+ marcas premium</strong> e mais de <strong>2.000 SKUs</strong> em skincare, maquiagem, capilares, perfumaria, chá e wellness — todos com padrão K-Beauty e P&D próprio.",
  productLines: [
    { name: "Sulwhasoo", tag: "Ícone luxo herbal", color: "from-amber-500/15 to-amber-700/5",
      text: "Marca top de skincare herbal coreano com ginseng vermelho — usado por celebridades globais.",
      items: ["First Care Serum", "Ginseng Renewing Cream", "Concentrated Ginseng Renewing Serum"] },
    { name: "Laneige", tag: "Hidratação premium", color: "from-sky-500/15 to-sky-700/5",
      text: "Best-seller mundial em hidratação — Water Sleeping Mask e Lip Sleeping Mask viralizaram no TikTok.",
      items: ["Water Sleeping Mask", "Lip Sleeping Mask", "Cream Skin", "Water Bank"] },
    { name: "Innisfree", tag: "Natural de Jeju", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Marca natural com ingredientes da ilha de Jeju: chá verde, orquídea vulcânica, camélia.",
      items: ["Green Tea Serum", "Volcanic Clay Mask", "Cica Balm", "No-Sebum Powder"] },
    { name: "Etude House", tag: "Jovem/coreano fun", color: "from-rose-500/15 to-rose-700/5",
      text: "Marca teen coreana — maquiagem colorida e affordable K-Beauty.",
      items: ["Play Color Eyes", "Tint Lip Balm", "Cushion Foundation", "Nail Enamel"] },
    { name: "Ryo & Mise-en-scène", tag: "Cabelo K-Beauty", color: "from-purple-500/15 to-purple-700/5",
      text: "Cuidados capilares premium coreanos — best-sellers em queda capilar e reparação.",
      items: ["Ryo Anti-Hair Loss", "Mise-en-scène Perfect Serum", "Damage Care"] },
    { name: "IOPE, HERA, Primera", tag: "Skincare científico", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Marcas premium science-based com bio-ciência, botânica orgânica e prestige feminino.",
      items: ["IOPE Retinol", "HERA Black Cushion", "Primera Alpine Berry"] },
  ],
  planTitle: "Plano de Compensação AmorePacific (Beauty Counselor Coreano)",
  planIntro:
    "Modelo <strong>direct selling coreano tradicional</strong> com Beauty Counselors — mescla venda porta-a-porta, consultoria personalizada e retail físico (Aritaum multi-brand). Diferente do MMN ocidental, tem estrutura de <strong>hierarquia gerencial</strong> em vez de bônus multinível profundos.",
  planRanks: [
    { rank: "Beauty Counselor", payout: "20-30% varejo", text: "Consultora independente vinculada a um shop." },
    { rank: "Senior Counselor", payout: "+ Bônus performance", text: "Meta anual de vendas premium." },
    { rank: "Team Leader", payout: "+ Override equipe", text: "Coordena grupo de 5-20 counselors." },
    { rank: "Shop Manager", payout: "Salário + comissão", text: "Gerente de loja Aritaum com base fixa." },
    { rank: "Regional Director", payout: "Elite Pool", text: "Topo — supervisiona múltiplas regiões da Coreia." },
  ],
  pros: [
    "Marca global de altíssimo prestígio (Forbes Global 2000)",
    "Portfólio riquíssimo (30+ marcas para diferentes públicos)",
    "P&D próprio — 500+ cientistas em Yongin",
    "Inovação real (pioneira em cushion foundation)",
    "Presença física + digital forte no mundo todo",
    "Sustentabilidade: metas net-zero até 2030",
  ],
  cons: [
    "Modelo direct selling menos alavancável que MMN tradicional",
    "Sem operação MMN oficial no Brasil (só varejo via importação)",
    "Estrutura hierárquica corporativa (não é MMN puro)",
    "Foco geográfico ainda muito concentrado em Coreia + China + Japão",
    "Preços premium (fora do orçamento de muitos consumidores)",
  ],
  presenceIntro:
    "Presente em <strong>50+ países da Ásia, Américas, Europa e Oriente Médio</strong> — com maior força na Coreia do Sul, China, Japão, EUA, Sudeste Asiático e mercados europeus premium.",
  countries: [
    "🇰🇷 Coreia do Sul", "🇨🇳 China", "🇯🇵 Japão", "🇭🇰 Hong Kong", "🇹🇼 Taiwan",
    "🇸🇬 Singapura", "🇲🇾 Malásia", "🇹🇭 Tailândia", "🇵🇭 Filipinas", "🇻🇳 Vietnã",
    "🇮🇩 Indonésia", "🇮🇳 Índia",
    "🇺🇸 EUA", "🇨🇦 Canadá",
    "🇫🇷 França", "🇬🇧 Reino Unido", "🇩🇪 Alemanha", "🇮🇹 Itália", "🇪🇸 Espanha",
    "🇦🇪 Emirados Árabes", "🇸🇦 Arábia Saudita",
    "🇦🇺 Austrália", "🇷🇺 Rússia",
  ],
  awards: [
    "Forbes Global 2000 — desde 2010",
    "Best K-Beauty Company (Vogue Korea, várias edições)",
    "Cosmetic Executive Women (CEW) — Sulwhasoo Awards",
    "Green Star (sustentabilidade Coreia)",
    "Cannes Lions (Innisfree — várias)",
  ],
  certifications: [
    "ISO 9001 / 14001 / 22716 (GMP cosmético)",
    "COSMOS Organic (Primera)",
    "Vegan Society (linhas selecionadas)",
    "Halal Certified (linhas selecionadas)",
    "EWG Verified (produtos específicos)",
    "PETA Approved (várias marcas)",
  ],
  faqs: [
    { q: "O que é a AmorePacific?",
      a: "É a maior empresa de cosméticos da Coreia do Sul, fundada em 1945 por Suh Sung-Whan, dona de mais de 30 marcas globais como Sulwhasoo, Laneige, Innisfree, Etude House, Mamonde, IOPE, HERA e Ryo. É a maior potência mundial de K-Beauty." },
    { q: "Quanto fatura a AmorePacific?",
      a: "Em 2025 o Grupo AmorePacific consolidou US$ 3,5 bilhões em receita, ocupando o Top 12 mundial em cosméticos e Forbes Global 2000." },
    { q: "A AmorePacific opera no Brasil?",
      a: "Não oficialmente como MMN. Marcas AmorePacific (Innisfree, Laneige, Sulwhasoo) chegam ao Brasil via importadores como Sephora Brasil, Beleza na Web e marketplaces internacionais. Não há operação direct selling oficial no país." },
    { q: "Quais são as principais marcas da AmorePacific?",
      a: "Sulwhasoo (luxo herbal), Laneige (hidratação — best-seller TikTok), Innisfree (natural de Jeju), Etude House (jovem/colorido), Mamonde (floral), IOPE (bio-ciência), HERA (moderno), Ryo (capilar), Primera (orgânico) — total de 30+ marcas." },
    { q: "Qual a diferença entre AmorePacific e LG H&H?",
      a: "Ambas são gigantes coreanas de cosméticos. AmorePacific (US$ 3,5 bi) é mais focada em K-Beauty pura com marcas icônicas globais. LG Household & Health Care (US$ 6 bi) é mais diversificada (household + beleza) e mais forte no mercado doméstico coreano." },
    { q: "O que é K-Beauty?",
      a: "K-Beauty (Korean Beauty) é o padrão cosmético sul-coreano baseado em rotinas de skincare multi-etapas, ingredientes botânicos (ginseng, chá verde, cica, snail mucin), inovação em texturas (cushion, sheet mask, essence) e foco em pele saudável. A AmorePacific é a principal referência mundial da categoria." },
    { q: "A AmorePacific inventou a cushion foundation?",
      a: "Sim. Em 2008 a marca IOPE (do grupo AmorePacific) lançou o primeiro Cushion Foundation do mundo — base compacta em esponja com aplicador integrado. A tecnologia foi patenteada e depois licenciada/copiada por Lancôme, Dior, YSL e dezenas de outras marcas globais." },
    { q: "Como a AmorePacific vende: MMN ou varejo?",
      a: "Modelo híbrido. Historicamente forte em Beauty Counselors (consultoras que fazem venda direta porta-a-porta na Coreia — pioneira desde 1964). Hoje também opera lojas Aritaum multi-brand, monobrand internacionais, e-commerce global e distribuição em Sephora, Ulta e Amazon." },
  ],
  founders: ["Suh Sung-Whan (서성환)"],
  foundingDate: "1945-09-05",
  foundingLocation: "Seul, Coreia do Sul",
  employees: 15000,
  alternateNames: ["아모레퍼시픽", "AmorePacific Corporation", "AP Group"],
  wikipediaUrl: "https://en.wikipedia.org/wiki/AmorePacific",
};

const AmorePacific = () => <CompanyPremiumPage data={data} />;
export default AmorePacific;
