import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "DXN Global",
  slug: "dxn-global",
  officialUrl: "https://www.dxn2u.com/",
  domain: "dxn2u.com",
  seoTitle: "DXN Global: MMN de Café Ganoderma e Cogumelos | Top 40 Mundial 2026",
  seoDescription:
    "DXN Global é a multinacional malaia de MMN especializada em café com ganoderma (cogumelo reishi) e produtos wellness. Faturamento de US$ 700 milhões, presença em 180+ países e 15 milhões de distribuidores.",
  rankingLabel: "TOP 40 MUNDIAL • DSN GLOBAL 100 2026",
  heroHeadlineSuffix: "O Rei Mundial do Café com Ganoderma",
  heroParagraph:
    "Fundada em 1993 pelo Dr. Lim Siow Jin na Malásia, a DXN é a líder mundial em produtos com Ganoderma (cogumelo reishi), especialmente café, com receita de US$ 700 milhões e presença em mais de 180 países — o maior alcance global entre as MMN asiáticas.",
  heroBadges: [
    { label: "32 anos", icon: "calendar" },
    { label: "180+ países", icon: "globe" },
    { label: "15 milhões de membros", icon: "users" },
    { label: "Ganoderma líder mundial", icon: "check" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 40", hint: "DSN Global 100" },
    { icon: "calendar", label: "Fundação", value: "1993", hint: "Alor Setar, Malásia" },
    { icon: "map", label: "País de Origem", value: "Malásia 🇲🇾", hint: "Sede em Alor Setar" },
    { icon: "globe", label: "Países", value: "180+", hint: "Maior alcance geográfico da Ásia" },
    { icon: "users", label: "Membros", value: "15 milhões+", hint: "Distribuidores e consumidores" },
    { icon: "package", label: "Produtos", value: "500+", hint: "Café Ganoderma, suplementos, higiene, alimentos" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 700 mi", hint: "Fonte: DSN Global 100" },
    { icon: "factory", label: "Fazendas próprias", value: "6", hint: "Ganoderma cultivado na Malásia" },
  ],
  aboutHtml: `
    <p>A <strong>DXN Marketing Sdn. Bhd.</strong> foi fundada em <strong>1993</strong> pelo <strong>Dr. Lim Siow Jin</strong>, doutor em engenharia pelo IIT (Índia) e especialista em Ganoderma. A sede fica em <strong>Alor Setar (Malásia)</strong> e a empresa cultiva <strong>Ganoderma (cogumelo reishi) nas próprias fazendas</strong>, garantindo controle total da cadeia produtiva.</p>
    <p>Seu produto mais famoso é o <strong>Lingzhi Coffee 3-em-1</strong> — café instantâneo com pó de Ganoderma e Ginseng, considerado um dos produtos mais vendidos do MMN mundial. A DXN também produz <strong>café preto, café latte, capuccino, chocolates funcionais, suplementos, cosméticos e produtos para casa</strong> — todos com Ganoderma ou ingredientes naturais.</p>
    <p>Com receita de <strong>US$ 700 milhões em 2025</strong>, presença em <strong>mais de 180 países</strong> e <strong>15 milhões de membros</strong>, a DXN ocupa o <strong>Top 40 do DSN Global 100 2026</strong>. É pioneira no modelo <strong>"1 Mundo, 1 Mercado, 1 DXN"</strong>, onde qualquer distribuidor no mundo pertence à mesma rede global unificada.</p>
  `,
  timelineTitle: "A jornada da DXN desde 1993",
  milestones: [
    { year: "1993", title: "Fundação pelo Dr. Lim Siow Jin", text: "Nasce em Alor Setar (Malásia) com Ganoderma como pilar da empresa." },
    { year: "1995", title: "Lançamento do Lingzhi Coffee", text: "Café 3-em-1 com Ganoderma vira o carro-chefe da empresa." },
    { year: "2000", title: "Expansão asiática", text: "Chegada às Filipinas, Indonésia, Índia, Tailândia e Cingapura." },
    { year: "2005", title: "Modelo 1 Mundo, 1 Mercado", text: "Adota rede global unificada — qualquer distribuidor patrocina em qualquer país." },
    { year: "2010", title: "Expansão para África e LATAM", text: "Chegada a Nigéria, Gana, Brasil, México e Colômbia." },
    { year: "2015", title: "US$ 500 mi", text: "Empresa cruza meio bilhão de dólares em receita anual." },
    { year: "2020", title: "180 países", text: "Consolidação como MMN de maior alcance geográfico da Ásia." },
    { year: "2026", title: "Top 40 mundial", text: "US$ 700 mi, 15 milhões de membros e liderança absoluta em Ganoderma." },
  ],
  productsIntro:
    "Portfólio completo com <strong>500+ produtos</strong> baseados em <strong>Ganoderma (cogumelo reishi), Spirulina, Cordyceps e ervas naturais</strong>. Cafés, chás, suplementos, cosméticos e produtos para casa.",
  productLines: [
    { name: "Café & Bebidas Ganoderma", tag: "Carro-chefe", color: "from-amber-500/15 to-amber-700/5",
      text: "Cafés instantâneos, capuccinos, chocolates e cocoa com Ganoderma. Produto mais vendido da empresa.",
      items: ["Lingzhi Coffee 3-em-1", "Café Preto Ganoderma", "Cocozhi", "Lingzhi Cappuccino"] },
    { name: "Suplementos Ganoderma", tag: "Wellness", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Cápsulas e pós de Ganoderma, Spirulina, Cordyceps — nutracêuticos com apelo natural.",
      items: ["RG (Reishi Gano)", "GL (Ganocelium)", "Spirulina Tablet", "Cordyceps Capsules"] },
    { name: "Cuidados Pessoais", tag: "Cosméticos", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Sabonetes, shampoos, cremes e cosméticos formulados com Ganoderma.",
      items: ["Ganozhi Toothpaste", "Ganozhi Soap", "Ganozhi Shampoo", "Skincare Line"] },
    { name: "Alimentos & Casa", tag: "Wellness diário", color: "from-blue-500/15 to-blue-700/5",
      text: "Chá, mel, azeite, temperos, produtos de limpeza ecológicos e complementos nutricionais.",
      items: ["Roselle Juice", "Cordyceps Tea", "Ganozhi Detergent", "Zhi Mocha"] },
  ],
  planTitle: "Plano de Compensação DXN (Uni-Nível 1 Mundo)",
  planIntro:
    "Modelo <strong>uni-nível global unificado</strong> (\"1 World, 1 Market, 1 DXN\"): qualquer distribuidor pode patrocinar em qualquer país do mundo na mesma rede. Bônus principal: 6 tipos de comissão + carro incentivo (DXN Car) + viagens.",
  planRanks: [
    { rank: "Membro DXN", payout: "25% desconto", text: "Cadastro básico grátis ou muito baixo — compra com desconto." },
    { rank: "Star Agent", payout: "+ Star Group Bonus 6-25%", text: "Ativa PV mínimo — recebe bônus por volume de grupo pessoal." },
    { rank: "Star Ruby / Star Diamond", payout: "+ Bônus Desenvolvimento 15%", text: "Múltiplas equipes ativas — bônus de desenvolvimento de rede." },
    { rank: "Crown Diamond", payout: "+ Leadership Bonus + DXN Car", text: "Elite qualificada — carro incentivo (Toyota/BMW) e bônus de liderança." },
    { rank: "Senior Crown / Executive Crown", payout: "+ Overriding Bonus 2%", text: "Top ranks — bônus sobre toda a rede global unificada." },
    { rank: "International Crown", payout: "Elite Pool + Casa", text: "Nível supremo — pool internacional + programa de casa (DXN House Bonus)." },
  ],
  pros: [
    "Modelo global unificado — patrocina em qualquer país",
    "Kit inicial praticamente gratuito (só cadastro)",
    "Produto de consumo diário (café) com alto giro",
    "Empresa 100% dona da produção (Ganoderma nas próprias fazendas)",
    "Presença em 180+ países — maior alcance mundial",
    "Sem taxa de manutenção mensal",
  ],
  cons: [
    "Café Ganoderma tem sabor específico (nem todos gostam)",
    "Concorrência acirrada com Organo Gold em nicho de café",
    "Bônus por ponto (PV) mais baixo que MMN premium ocidental",
    "Menor visibilidade de marca no Brasil vs Herbalife",
    "Renda alta exige rede muito grande e internacional",
  ],
  presenceIntro:
    "A DXN opera em <strong>mais de 180 países</strong> — o maior alcance geográfico entre todas as empresas de MMN asiáticas. Especialmente forte na <strong>Índia, Filipinas, Indonésia, África e Oriente Médio</strong>.",
  countries: [
    "🇲🇾 Malásia", "🇸🇬 Singapura", "🇮🇳 Índia", "🇵🇭 Filipinas", "🇮🇩 Indonésia",
    "🇹🇭 Tailândia", "🇻🇳 Vietnã", "🇰🇭 Camboja", "🇱🇰 Sri Lanka", "🇵🇰 Paquistão",
    "🇦🇪 Emirados Árabes", "🇸🇦 Arábia Saudita", "🇹🇷 Turquia", "🇪🇬 Egito", "🇳🇬 Nigéria",
    "🇬🇭 Gana", "🇰🇪 Quênia", "🇿🇦 África do Sul", "🇺🇸 EUA", "🇨🇦 Canadá",
    "🇲🇽 México", "🇧🇷 Brasil", "🇨🇴 Colômbia", "🇵🇪 Peru", "🇦🇷 Argentina",
    "🇬🇧 Reino Unido", "🇪🇸 Espanha", "🇮🇹 Itália", "🇩🇪 Alemanha", "🇫🇷 França",
    "🇷🇺 Rússia", "🇦🇺 Austrália", "🇯🇵 Japão", "🇨🇳 China", "🇭🇰 Hong Kong",
  ],
  awards: [
    "DSN Global 100 — Top 40 (desde 2010)",
    "MCA Compassionate Corporate Award (Malásia)",
    "Brand Laureate Best Brand Award",
    "SME Rising Star Award",
    "Dr. Lim Siow Jin — Legend in Direct Selling",
  ],
  certifications: [
    "GMP (Good Manufacturing Practice)",
    "MeSTI (Malásia)",
    "Halal Certified",
    "ISO 9001 / 14001",
    "TGA (Austrália)",
    "USDA Organic (produtos selecionados)",
  ],
  faqs: [
    { q: "O que é a DXN Global?",
      a: "É uma multinacional malaia de marketing multinível fundada em 1993 pelo Dr. Lim Siow Jin, especializada em produtos com Ganoderma (cogumelo reishi) — principalmente café instantâneo Lingzhi. Presente em 180+ países e uma das maiores MMN da Ásia." },
    { q: "Quanto fatura a DXN em 2026?",
      a: "A DXN faturou US$ 700 milhões em 2025, ocupando o Top 40 do ranking Direct Selling News Global 100 2026 — a segunda maior MMN da Malásia atrás apenas da Amway asiática." },
    { q: "A DXN opera no Brasil?",
      a: "Sim, a DXN tem operação oficial no Brasil desde 2010, com escritório e logística local. Possui comunidade brasileira ativa em várias regiões, especialmente em São Paulo, Rio, Minas e Nordeste." },
    { q: "O que é o Lingzhi Coffee 3-em-1 da DXN?",
      a: "É o produto carro-chefe da DXN — café instantâneo 3-em-1 (café, creme, açúcar) com pó de Ganoderma Lucidum (cogumelo reishi) e Ginseng. Combina o sabor do café com propriedades funcionais do reishi, sendo um dos produtos mais vendidos do MMN mundial." },
    { q: "Como funciona o modelo '1 World, 1 Market' da DXN?",
      a: "É um sistema global unificado onde qualquer distribuidor DXN pode patrocinar novos membros em qualquer país onde a empresa opera (180+). Toda a rede pertence à mesma linha descendente global, sem barreiras geográficas para bonificação." },
    { q: "Quanto custa começar na DXN?",
      a: "O cadastro de membro DXN é praticamente gratuito ou custa muito pouco (US$ 3-10 dependendo do país) — um dos menores custos de entrada do setor MMN mundial. Basta o kit inicial de produtos mínimos para consumo próprio." },
    { q: "DXN é pirâmide financeira?",
      a: "Não. A DXN é uma empresa de MMN legítima com 32 anos de mercado, 6 fazendas próprias de Ganoderma na Malásia, receita de US$ 700 mi/ano e produtos reais consumidos massivamente ao consumidor final. Listada no DSN Global 100 há mais de 15 anos." },
    { q: "O que é Ganoderma e por que a DXN usa?",
      a: "Ganoderma Lucidum (reishi ou lingzhi) é um cogumelo medicinal usado há mais de 2.000 anos na medicina tradicional chinesa por suas propriedades imunomoduladoras e adaptogênicas. A DXN cultiva Ganoderma nas próprias fazendas na Malásia com padrão de qualidade rigoroso." },
    { q: "Como funciona o plano de compensação da DXN?",
      a: "É um plano uni-nível global com 6 tipos de bônus: Star Group Bonus (6-25%), Development Bonus (15%), Leadership Bonus, Overriding Bonus (2% global), Travel Seminar Fund e DXN Car Fund (Toyota/BMW para ranks superiores). Todos pagam globalmente sem barreiras geográficas." },
    { q: "Vale a pena entrar na DXN em 2026?",
      a: "Sim para quem valoriza baixíssimo custo de entrada, produto de consumo diário (café) e modelo global unificado. É especialmente atrativa para quem tem contatos internacionais na Ásia, África ou Oriente Médio onde a marca é muito forte." },
  ],
  founders: ["Dr. Lim Siow Jin"],
  foundingDate: "1993-01-01",
  foundingLocation: "Alor Setar, Kedah, Malásia",
  employees: 2500,
  alternateNames: ["DXN", "DXN Marketing", "DXN International"],
};

const DXNGlobal = () => <CompanyPremiumPage data={data} />;
export default DXNGlobal;
