import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Forever Living Products",
  slug: "forever-living",
  officialUrl: "https://www.foreverliving.com/",
  domain: "foreverliving.com",
  seoTitle: "Forever Living: A Maior Produtora de Aloe Vera do Mundo | MMN 2026",
  seoDescription:
    "Forever Living é a maior produtora e comercializadora de aloe vera do mundo, com US$ 1,5 bi de receita e atuação em 160+ países. Conheça produtos, plano de marketing e história.",
  rankingLabel: "TOP 25 MUNDIAL • LÍDER GLOBAL EM ALOE VERA • 2026",
  heroHeadlineSuffix: "A Líder Mundial em Aloe Vera",
  heroParagraph:
    "Fundada em 1978 no Arizona, a Forever Living Products é a maior produtora, fabricante e distribuidora de produtos à base de aloe vera do mundo, com mais de 9,5 milhões de distribuidores em 160+ países e US$ 1,5 bilhão em receita anual.",
  heroBadges: [
    { label: "Maior produtora de aloe vera", icon: "check" },
    { label: "45+ anos", icon: "calendar" },
    { label: "160+ países", icon: "globe" },
    { label: "9,5 mi distribuidores", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 25", hint: "Líder mundial em aloe vera" },
    { icon: "calendar", label: "Fundação", value: "1978", hint: "45+ anos" },
    { icon: "map", label: "País de Origem", value: "EUA 🇺🇸", hint: "Scottsdale, Arizona" },
    { icon: "globe", label: "Países & Territórios", value: "160+", hint: "Maior alcance do MMN" },
    { icon: "users", label: "Distribuidores", value: "9,5 mi+", hint: "Forever Business Owners" },
    { icon: "leaf", label: "Plantação Própria", value: "32 mi+ pés", hint: "Maior plantação privada de aloe do mundo" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 1,5 bi", hint: "Fonte: Business For Home" },
    { icon: "package", label: "Produtos no Portfólio", value: "150+", hint: "Suplementos, cosméticos, abelhas" },
  ],
  aboutHtml: `
    <p>A <strong>Forever Living Products International, LLC</strong> é uma multinacional americana fundada em <strong>1978</strong> por <em>Rex Maughan</em>, em Scottsdale, Arizona. É a <strong>maior produtora, fabricante e distribuidora de produtos à base de aloe vera (babosa) do mundo</strong>.</p>
    <p>A Forever opera o ciclo completo do aloe — <strong>"da plantação ao frasco"</strong> — em suas próprias plantações no Texas, República Dominicana e México, com mais de <strong>32 milhões de pés de babosa</strong> (a maior plantação privada do mundo). Mantém também a <strong>Forever Bee</strong>, segunda maior produtora privada de produtos apícolas do planeta.</p>
    <p>Ocupa o <strong>Top 25 mundial</strong> no ranking Business For Home 2026 com receita de <strong>US$ 1,5 bilhão</strong>, presença em <strong>mais de 160 países</strong> (o maior alcance geográfico do setor de MMN) e mais de <strong>9,5 milhões de Forever Business Owners</strong>. É 100% familiar e privada, sem capital aberto.</p>
  `,
  milestones: [
    { year: "1978", title: "Fundação em Scottsdale", text: "Rex Maughan funda a Forever Living Products no Arizona, com a missão de levar os benefícios da babosa ao mundo." },
    { year: "1980", title: "Aloe Vera Gel", text: "Lançamento do Forever Aloe Vera Gel, primeiro produto puro de aloe vera estabilizado da indústria — vira o carro-chefe da marca." },
    { year: "1991", title: "Selo IASC", text: "A Forever recebe o primeiro selo do International Aloe Science Council (IASC), certificando a pureza dos produtos." },
    { year: "1994", title: "Expansão para o Brasil", text: "Inicia operações no Brasil, hoje um dos maiores mercados da empresa na América Latina." },
    { year: "2000", title: "Aloe Vera Plantations", text: "Forever expande plantações para a República Dominicana e México, tornando-se a maior produtora privada de aloe vera do mundo." },
    { year: "2014", title: "Aquisição da Aloe Vera of America", text: "Forever consolida toda a cadeia produtiva, do plantio ao envase, com fábrica própria no Texas." },
    { year: "2020", title: "Transformação digital", text: "Forever lança e-commerce próprio e ferramentas digitais para Forever Business Owners." },
    { year: "2026", title: "Liderança em aloe consolidada", text: "Forever mantém posição de maior produtora mundial de aloe vera e Top 25 mundial Business For Home 2026 com US$ 1,5 bilhão." },
  ],
  productLines: [
    { name: "Forever Aloe Vera Gel", tag: "Bebida Funcional Premium", color: "from-emerald-500/15 to-emerald-700/5",
      text: "O carro-chefe absoluto. Gel puro de aloe vera estabilizado, com 99,7% de pureza, primeiro produto do mundo certificado pelo International Aloe Science Council.",
      items: ["Aloe Vera Gel Original", "Aloe Berry Nectar", "Aloe Peaches", "Forever Freedom", "Aloe2Go"] },
    { name: "Forever Nutrition", tag: "Suplementos Nutricionais", color: "from-amber-500/15 to-amber-700/5",
      text: "Linha completa de multivitamínicos, ômega-3, probióticos e suplementos esportivos.",
      items: ["Forever Daily", "Forever Active Probiotic", "Forever Arctic Sea", "Fields of Greens", "Forever Calcium"] },
    { name: "Forever C9 / F15 / Vital5", tag: "Programas de Bem-estar", color: "from-rose-500/15 to-rose-700/5",
      text: "Programas estruturados de detox, controle de peso e nutrição diária — entre os mais vendidos do setor.",
      items: ["Forever C9 (9 dias)", "F15 (15 dias)", "Vital5", "Lite Ultra Shake"] },
    { name: "Forever Bee", tag: "Produtos Apícolas", color: "from-amber-600/15 to-amber-800/5",
      text: "Segunda maior produtora privada de produtos apícolas do mundo: mel, geleia real, pólen e própolis.",
      items: ["Forever Bee Pollen", "Bee Honey", "Bee Propolis", "Royal Jelly"] },
    { name: "Sonya Skincare", tag: "Skincare com Aloe", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linha de skincare com aloe vera como ingrediente principal, fórmulas anti-idade e cuidados diários.",
      items: ["Sonya Hydrate", "Sonya Refine", "Sonya Renew", "Sonya Soothe"] },
    { name: "Forever Body & Personal Care", tag: "Higiene Pessoal", color: "from-sky-500/15 to-sky-700/5",
      text: "Linha completa de higiene corporal e oral à base de aloe vera, sem parabenos e dermatologicamente testados.",
      items: ["Aloe Bath Gelée", "Aloe Lips", "Aloe Propolis Crème", "Forever Bright Toothgel", "Aloe Hand Soap"] },
  ],
  planTitle: "Plano de Marketing Forever Living",
  planIntro:
    "A Forever opera um plano <strong>multinível tradicional com lucro de até 43% sobre a tabela</strong>, mais bônus de desenvolvimento e liderança. Já distribuiu mais de <strong>US$ 4,5 bilhões em bônus</strong> aos Forever Business Owners desde 1978.",
  planRanks: [
    { rank: "Novo Distribuidor", payout: "15% lucro", text: "Cadastro como Forever Business Owner (FBO)." },
    { rank: "Assistente Supervisor", payout: "30% lucro", text: "Atinge 2 CC (Case Credits) em 2 meses consecutivos." },
    { rank: "Supervisor", payout: "35% lucro", text: "Atinge 25 CC em 2 meses consecutivos." },
    { rank: "Assistente Gerente", payout: "43% lucro + bônus", text: "75 CC em 2 meses consecutivos — primeiro nível de bônus de equipe." },
    { rank: "Gerente", payout: "+ Bônus de Liderança", text: "120 CC em 2 meses consecutivos." },
    { rank: "Gerente Sênior", payout: "+ Bônus Globais", text: "2 gerentes patrocinados em diferentes pernas." },
    { rank: "Soaring Manager", payout: "+ Profit Sharing", text: "Mantém produção por 6 meses consecutivos." },
    { rank: "Diamond / Sapphire / Diamond Sapphire", payout: "Topo do Plano", text: "Patamar mais alto com participação em pools globais e viagens internacionais (Eagle Manager Retreat)." },
  ],
  pros: [
    "Maior produtora mundial de aloe vera (cadeia 100% própria)",
    "Presença em 160+ países (maior alcance geográfico do setor)",
    "Produtos consumíveis com alta recompra",
    "Lucro de revenda alto (até 43%)",
    "Programa C9 amplamente reconhecido para detox",
    "Empresa 100% familiar, sem capital aberto (estabilidade)",
  ],
  cons: [
    "Foco concentrado em aloe vera (menos diversificação)",
    "Estoque mínimo é parte do modelo",
    "Plano de carreira tradicional (não binário)",
    "Concorrência crescente em aloe vera no varejo",
    "Treinamento depende muito do upline",
  ],
  countries: [
    "🇺🇸 EUA", "🇨🇦 Canadá", "🇲🇽 México", "🇧🇷 Brasil", "🇦🇷 Argentina", "🇨🇴 Colômbia",
    "🇨🇱 Chile", "🇵🇪 Peru", "🇩🇴 Rep. Dominicana", "🇬🇧 Reino Unido", "🇩🇪 Alemanha", "🇫🇷 França",
    "🇮🇹 Itália", "🇪🇸 Espanha", "🇵🇹 Portugal", "🇵🇱 Polônia", "🇷🇺 Rússia",
    "🇮🇳 Índia", "🇨🇳 China", "🇯🇵 Japão", "🇰🇷 Coreia do Sul", "🇹🇭 Tailândia", "🇲🇾 Malásia",
    "🇮🇩 Indonésia", "🇵🇭 Filipinas", "🇿🇦 África do Sul", "🇳🇬 Nigéria", "🇪🇬 Egito",
    "🇸🇦 Arábia Saudita", "🇦🇪 Emirados Árabes", "🇦🇺 Austrália",
  ],
  awards: [
    "Top 25 Direct Selling News Global 100 — 2026",
    "Selo IASC — International Aloe Science Council (Pioneira)",
    "Best Place to Work Arizona",
    "Forever Giving Foundation — US$ 100 mi+ em filantropia",
    "Prêmio ABEVD de Vendas Diretas",
  ],
  certifications: [
    "IASC (International Aloe Science Council)",
    "Kosher (Orthodox Union)",
    "Halal Certified",
    "ISO 9001 / ISO 14001",
    "GMP — Good Manufacturing Practices",
    "ANVISA (operação Brasil)",
  ],
  faqs: [
    { q: "A Forever Living é uma empresa séria?",
      a: "Sim. A Forever Living Products tem mais de 45 anos de história, opera em 160+ países, fatura US$ 1,5 bilhão anuais e é membro de Direct Selling Associations em todo o mundo, incluindo a ABEVD no Brasil." },
    { q: "Quanto custa o kit de início da Forever?",
      a: "O kit inicial Forever Business Owner (FBO) no Brasil custa entre R$ 350 e R$ 850, dependendo da versão escolhida (Kit Inicial, Touch of Forever ou Kit Premium)." },
    { q: "Quais são os principais produtos da Forever Living?",
      a: "O carro-chefe é o Forever Aloe Vera Gel (gel puro de babosa). Outros destaques: Forever Active Probiotic, Forever Daily, programas C9 e F15 (detox e controle de peso), linha Sonya (skincare) e Forever Bee (produtos apícolas)." },
    { q: "O que é o programa C9 da Forever?",
      a: "É um programa de 9 dias de limpeza e renovação corporal baseado em Aloe Vera Gel, Forever Garcinia Plus, Forever Therm e Forever Lite Ultra. É um dos programas mais vendidos do setor." },
    { q: "Quanto a Forever distribui em bônus?",
      a: "Desde 1978, a Forever Living já distribuiu mais de US$ 4,5 bilhões em bônus aos seus Forever Business Owners no mundo todo." },
    { q: "Em quantos países a Forever opera?",
      a: "A Forever Living está presente em mais de 160 países — o maior alcance geográfico de qualquer empresa de MMN do mundo. No Brasil opera desde 1994." },
    { q: "A Forever testa seus produtos?",
      a: "Sim. Todos os produtos são fabricados em instalações certificadas GMP, com selo IASC para aloe vera. A Forever foi a primeira empresa do mundo a receber esse selo, em 1991." },
  ],
  founders: ["Rex Maughan"],
  foundingDate: "1978-05-15",
  foundingLocation: "Scottsdale, Arizona, EUA",
  employees: 4500,
  alternateNames: ["Forever Living Products International", "Forever"],
  wikipediaUrl: "https://en.wikipedia.org/wiki/Forever_Living_Products",
};

const ForeverLiving = () => <CompanyPremiumPage data={data} />;
export default ForeverLiving;
