import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Herbalife",
  slug: "herbalife",
  officialUrl: "https://www.herbalife.com.br/",
  domain: "herbalife.com",
  seoTitle: "Herbalife Nutrition: A Gigante Mundial da Nutrição | Ranking #2 2026",
  seoDescription:
    "Herbalife é a #2 do ranking mundial 2026 com US$ 4,5 bi em receita. Conheça a história, produtos, shake Fórmula 1, plano de marketing, países e tudo sobre a maior empresa de nutrição em marketing multinível do mundo.",
  rankingLabel: "#2 RANKING MUNDIAL • BUSINESS FOR HOME 2026",
  heroHeadlineSuffix: "A Gigante Mundial da Nutrição",
  heroParagraph:
    "Fundada em 1980 na Califórnia, a Herbalife Nutrition é a maior empresa de nutrição em marketing multinível do mundo, com mais de 2,3 milhões de distribuidores independentes em mais de 95 países e US$ 4,5 bilhões em receita anual.",
  heroBadges: [
    { label: "Receita verificada", icon: "check" },
    { label: "45+ anos", icon: "calendar" },
    { label: "95+ países", icon: "globe" },
    { label: "2,3 mi de distribuidores", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "#2", hint: "Maior empresa de nutrição MMN" },
    { icon: "calendar", label: "Fundação", value: "1980", hint: "45+ anos de mercado" },
    { icon: "map", label: "País de Origem", value: "EUA 🇺🇸", hint: "Los Angeles, Califórnia" },
    { icon: "globe", label: "Países & Territórios", value: "95+", hint: "Operação em 5 continentes" },
    { icon: "users", label: "Distribuidores Independentes", value: "2,3 mi+", hint: "Members ativos em 2025" },
    { icon: "package", label: "Categorias de Produtos", value: "100+", hint: "Nutrição, performance e bem-estar" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 4,5 bi", hint: "Fonte: Business For Home" },
    { icon: "factory", label: "Funcionários Globais", value: "11.000+", hint: "P&D, fábricas e suporte" },
  ],
  aboutHtml: `
    <p>A <strong>Herbalife Nutrition</strong> é uma multinacional americana fundada em <strong>1980</strong> por <em>Mark Hughes</em>, em Los Angeles, Califórnia. Criada com a missão de "mudar a vida das pessoas com nutrição de qualidade e oportunidade econômica", a Herbalife se tornou a <strong>maior empresa de nutrição em marketing multinível do mundo</strong>.</p>
    <p>Hoje listada na Bolsa de Nova York (NYSE: HLF), a <strong>Herbalife</strong> é a <strong>#2 do ranking Business For Home 2026</strong>, com receita anual de <strong>US$ 4,5 bilhões</strong>, presença em <strong>mais de 95 países</strong> e mais de <strong>2,3 milhões de distribuidores independentes</strong>. Seu carro-chefe absoluto é o icônico <strong>Shake Fórmula 1</strong>, o substituto de refeição mais vendido do mundo.</p>
    <p>A empresa investe pesadamente em <strong>ciência e nutrição</strong>: mantém o Mark Hughes Cellular and Molecular Nutrition Laboratory na UCLA e o <strong>Herbalife Nutrition Institute</strong>, com um conselho consultivo formado por Nobel laureates e PhDs em nutrição. Produtos como <strong>Fórmula 1, Herbal Tea Concentrate, Thermo Complete e Niteworks</strong> são vendidos em milhões de Clubes de Nutrição (Espaços VIDA) em todo o mundo.</p>
  `,
  timelineTitle: "Da garagem em Los Angeles ao topo da nutrição mundial",
  milestones: [
    { year: "1980", title: "Fundação da Herbalife", text: "Mark Hughes lança a Herbalife na Califórnia com um único produto: o Shake Fórmula 1, criado em homenagem à sua mãe." },
    { year: "1982", title: "Expansão para o Canadá", text: "Primeira operação internacional, marcando o início da escalada global." },
    { year: "1986", title: "Abertura de capital", text: "A Herbalife abre capital na NASDAQ, virando uma das primeiras MMNs listadas em bolsa." },
    { year: "1995", title: "Entrada no Brasil", text: "A Herbalife do Brasil é fundada e se torna rapidamente um dos 3 maiores mercados globais." },
    { year: "2002", title: "Listagem na NYSE", text: "Migra para a Bolsa de Nova York (NYSE: HLF), reforçando governança corporativa." },
    { year: "2004", title: "Conselho Nutricional", text: "Cria o Herbalife Nutrition Advisory Board com cientistas do mundo todo, incluindo Nobel laureates." },
    { year: "2014", title: "Marca Reformulada", text: "Reposicionamento global como Herbalife Nutrition, focando 100% no segmento de nutrição." },
    { year: "2016", title: "Acordo com a FTC", text: "Após investigação, a FTC reconhece o modelo de venda direta da Herbalife e a empresa paga acordo recorde, reforçando compliance." },
    { year: "2020", title: "Boom dos Espaços VIDA", text: "Os Clubes de Nutrição (Espaços VIDA) ultrapassam 100.000 unidades no mundo, fenômeno especialmente forte no Brasil e México." },
    { year: "2026", title: "Top 2 Mundial", text: "Mantém posição #2 no ranking Business For Home com US$ 4,5 bilhões em receita anual." },
  ],
  productsIntro:
    "Mais de <strong>100 produtos</strong> nas linhas de nutrição básica, controle de peso, performance esportiva, beleza externa e energia, com fórmulas desenvolvidas pelo Herbalife Nutrition Institute.",
  productLines: [
    { name: "Fórmula 1 Shake", tag: "Substituto de Refeição #1 do Mundo", color: "from-amber-500/15 to-amber-700/5",
      text: "O shake substituto de refeição mais vendido do mundo, com proteína de soja, 21 vitaminas e minerais. Mais de 1 milhão de shakes consumidos por dia globalmente.",
      items: ["Baunilha Cremosa", "Cookies & Cream", "Chocolate Cremoso", "Morango", "Banana", "Frutas Tropicais"] },
    { name: "Herbalife24", tag: "Performance Esportiva", color: "from-rose-500/15 to-rose-700/5",
      text: "Linha completa de nutrição esportiva certificada NSF for Sport, usada por atletas profissionais e equipes como LA Galaxy e Cristiano Ronaldo (parceria histórica).",
      items: ["Hydrate", "CR7 Drive", "Rebuild Strength", "Rebuild Endurance", "Prolong", "Restore"] },
    { name: "Chá Herbal", tag: "Energia & Termogênese", color: "from-emerald-500/15 to-emerald-700/5",
      text: "O lendário Herbal Tea Concentrate combina chá verde, chá preto, cardamomo e malva — base dos Clubes de Nutrição em todo o Brasil.",
      items: ["Original", "Limão", "Pêssego", "Framboesa", "Canela"] },
    { name: "Niteworks & Cell Activator", tag: "Saúde Celular", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Suplementos premium criados em parceria com o Dr. Louis Ignarro (Nobel de Medicina 1998), focados em saúde cardiovascular e energia celular.",
      items: ["Niteworks", "Cell Activator", "Activated Fiber", "Aloe Concentrate"] },
    { name: "Skin & Outer Nutrition", tag: "Beleza Externa", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linha Herbalife SKIN com 7 produtos clean beauty, sem parabenos, sem sulfatos e dermatologicamente testados.",
      items: ["Polishing Citrus Cleanser", "Soothing Aloe Cleanser", "Daily Glow Moisturizer", "Hydrating Eye Cream"] },
    { name: "Controle de Peso", tag: "Programa Lifestyle", color: "from-sky-500/15 to-sky-700/5",
      text: "Programas estruturados de café da manhã saudável, controle de peso e ganho de massa magra, base da operação dos Clubes.",
      items: ["Café da Manhã Saudável", "Programa Avançado", "Thermo Complete", "Total Control", "Cell-U-Loss"] },
  ],
  planTitle: "Plano de Marketing Herbalife (Stairstep Breakaway)",
  planIntro:
    "O Plano de Marketing da Herbalife é um dos mais antigos e bem testados do MMN, baseado em <strong>desconto progressivo (de 25% a 50%)</strong>, royalties de até 5% e bônus de produção. Já distribuiu mais de <strong>US$ 39 bilhões</strong> em ganhos para distribuidores desde 1980.",
  planRanks: [
    { rank: "Member (Distribuidor)", payout: "25% desconto", text: "Entrada inicial via Kit HMP, com acesso imediato ao desconto de 25%." },
    { rank: "Senior Consultant", payout: "35% desconto", text: "1.000 Volume Points (VP) acumulados — aumento de margem para 35%." },
    { rank: "Success Builder", payout: "42% desconto", text: "1 pedido de 1.000 VP em um único mês — eleva o desconto a 42%." },
    { rank: "Qualified Producer", payout: "42% + ganhos de royalty", text: "2.500 VP em 1 a 3 meses consecutivos — começa a ganhar bônus de patrocínio." },
    { rank: "Supervisor", payout: "50% desconto + 5% Royalty", text: "4.000 VP em 1 mês ou 2.500 + 2.500 em 2 meses — desbloqueia royalties de até 3 níveis." },
    { rank: "World Team", payout: "+ Bônus Produção 2%", text: "10.000 VP em 1 mês — primeira graduação de elite." },
    { rank: "Global Expansion Team (GET)", payout: "+ 2% a 4% Produção", text: "1.000 Royalty Points em 3 meses consecutivos." },
    { rank: "Millionaire Team", payout: "+ Bônus Produção 4%", text: "4.000 Royalty Points em 3 meses consecutivos." },
    { rank: "President's Team", payout: "+ Bônus Produção 6%", text: "10.000 Royalty Points em 3 meses — patamar dos top earners globais." },
    { rank: "Chairman's Club", payout: "Topo do Plano", text: "Atingido por apenas 60+ líderes no mundo inteiro — reconhecimento máximo." },
  ],
  pros: [
    "Marca mais reconhecida em nutrição no mundo",
    "Produto consumível com alta recompra mensal (Shake Fórmula 1)",
    "Sistema de Clubes de Nutrição (Espaços VIDA) com modelo presencial validado",
    "Empresa listada em bolsa (NYSE: HLF) com transparência financeira",
    "Plano de marketing antigo, estável e amplamente comprovado",
    "Treinamento robusto e eventos internacionais (Extravaganza)",
  ],
  cons: [
    "Mercado brasileiro extremamente competitivo entre distribuidores",
    "Necessidade de manter volume mensal para sustentar graduações altas",
    "Foco quase exclusivo em nutrição (pouca diversificação de categoria)",
    "Margem por produto menor do que em concorrentes asiáticos",
    "Modelo de Clubes exige investimento físico inicial",
  ],
  presenceIntro:
    "Principais mercados em 2025: <strong>EUA, México, Brasil, China, Índia, Itália, Coreia do Sul e Espanha</strong> respondem por mais de 75% da receita global.",
  countries: [
    "🇺🇸 EUA", "🇲🇽 México", "🇧🇷 Brasil", "🇨🇦 Canadá", "🇦🇷 Argentina", "🇨🇴 Colômbia",
    "🇨🇱 Chile", "🇵🇪 Peru", "🇨🇳 China", "🇰🇷 Coreia do Sul", "🇯🇵 Japão", "🇮🇳 Índia",
    "🇮🇩 Indonésia", "🇲🇾 Malásia", "🇹🇭 Tailândia", "🇻🇳 Vietnã", "🇵🇭 Filipinas",
    "🇮🇹 Itália", "🇪🇸 Espanha", "🇵🇹 Portugal", "🇩🇪 Alemanha", "🇫🇷 França", "🇬🇧 Reino Unido",
    "🇷🇺 Rússia", "🇹🇷 Turquia", "🇦🇪 Emirados Árabes", "🇿🇦 África do Sul", "🇦🇺 Austrália",
  ],
  awards: [
    "#2 Direct Selling News Global 100 — 2026",
    "Forbes — Top 100 Maiores Empregadores Globais",
    "Patrocinadora oficial da CONMEBOL Libertadores (2024-2026)",
    "Parceria histórica com Cristiano Ronaldo (CR7 Drive)",
    "Prêmio ABEVD — Excelência em Vendas Diretas (Brasil)",
    "Forbes World's Best Employers (várias edições)",
  ],
  certifications: [
    "NSF Certified for Sport (linha Herbalife24)",
    "ISO 9001 (Gestão da Qualidade)",
    "ISO 14001 (Gestão Ambiental)",
    "Boas Práticas de Fabricação (BPF) ANVISA",
    "USP Verified em fábricas selecionadas",
    "Certificação Kosher e Halal em produtos selecionados",
  ],
  faqs: [
    { q: "A Herbalife é uma empresa segura ou é pirâmide?",
      a: "A Herbalife Nutrition é uma empresa pública listada na Bolsa de Nova York (NYSE: HLF) desde 2002 e regulada pela SEC, com mais de 45 anos de história. Em 2016, após investigação aprofundada da FTC americana, a empresa foi formalmente reconhecida como modelo legítimo de venda direta. No Brasil é regulada pela ABEVD e ANVISA." },
    { q: "Quanto custa começar como Distribuidor Herbalife?",
      a: "O Kit HMP (Herbalife Member Pack) custa entre R$ 240 e R$ 450 no Brasil, dependendo da versão. Não há mensalidade obrigatória — apenas uma renovação anual em torno de R$ 130. Garantia de devolução de 100% em até 90 dias." },
    { q: "Quais são os principais produtos da Herbalife?",
      a: "O carro-chefe é o Shake Fórmula 1, substituto de refeição mais vendido do mundo. Outros destaques: Herbal Tea Concentrate (chá), linha Herbalife24 de performance esportiva, Niteworks, Aloe Concentrate, Thermo Complete e a linha Herbalife SKIN." },
    { q: "O que é um Clube de Nutrição (Espaço VIDA) da Herbalife?",
      a: "É um modelo de negócio criado por distribuidores Herbalife em que clientes consomem shakes e chás no local, com acompanhamento de bem-estar. No Brasil existem mais de 30.000 Clubes ativos, sendo o maior mercado de Espaços VIDA do mundo." },
    { q: "Quanto fatura a Herbalife?",
      a: "Em 2025 a Herbalife faturou US$ 4,5 bilhões, ocupando a posição #2 no ranking mundial Business For Home 2026 das maiores empresas de vendas diretas." },
    { q: "Como funciona o plano de marketing da Herbalife?",
      a: "É um plano Stairstep Breakaway clássico, com descontos progressivos de 25% a 50%, royalties de até 5% sobre 3 níveis e bônus de produção que chegam a 6% no nível President's Team. O topo é o Chairman's Club, com apenas algumas dezenas de líderes globalmente." },
    { q: "A Herbalife é regulamentada no Brasil?",
      a: "Sim. A Herbalife do Brasil opera desde 1995, é membro da ABEVD e tem todos os seus produtos registrados na ANVISA, com Certificado de Boas Práticas de Fabricação." },
    { q: "Qual a diferença entre Herbalife e outras empresas de MMN?",
      a: "A Herbalife é a única empresa de venda direta listada na NYSE focada 100% em nutrição. Tem o sistema de Clubes de Nutrição (Espaços VIDA) como diferencial, conselho científico com Nobel laureates e o produto-âncora mais vendido do mundo (Shake Fórmula 1)." },
  ],
  founders: ["Mark Hughes"],
  foundingDate: "1980-02-01",
  foundingLocation: "Los Angeles, Califórnia, EUA",
  employees: 11000,
  alternateNames: ["Herbalife Nutrition", "Herbalife Ltd."],
  wikipediaUrl: "https://pt.wikipedia.org/wiki/Herbalife",
};

const Herbalife = () => <CompanyPremiumPage data={data} />;
export default Herbalife;
