import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Hinode",
  slug: "hinode",
  officialUrl: "https://www.hinode.com.br/",
  domain: "hinode.com.br",
  seoTitle: "Hinode: A Gigante Brasileira do Marketing Multinível | Plano Hinode 2026",
  seoDescription:
    "Hinode é uma das maiores empresas brasileiras de venda direta, com mais de 1 milhão de consultores e portfólio de cosméticos, perfumaria e nutrição. Conheça a história, produtos e o Plano Hinode.",
  rankingLabel: "MAIOR MMN 100% BRASILEIRO • RANKING NACIONAL 2026",
  heroHeadlineSuffix: "A Gigante Brasileira do Multinível",
  heroParagraph:
    "Fundada em 1988 em São Paulo, a Hinode é uma das maiores empresas brasileiras de marketing multinível, com mais de 1 milhão de Consultores Hinode em 5 países, portfólio diversificado em perfumaria, cosméticos, nutrição e cuidados pessoais.",
  heroBadges: [
    { label: "100% Brasileira", icon: "check" },
    { label: "35+ anos", icon: "calendar" },
    { label: "Brasil + 4 países", icon: "globe" },
    { label: "1 mi+ consultores", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Posição no Brasil", value: "Top 5", hint: "Maior MMN 100% brasileiro" },
    { icon: "calendar", label: "Fundação", value: "1988", hint: "35+ anos de história" },
    { icon: "map", label: "Sede", value: "São Paulo 🇧🇷", hint: "Capital paulista" },
    { icon: "globe", label: "Países", value: "5", hint: "Brasil, Portugal, EUA, México, Angola" },
    { icon: "users", label: "Consultores Hinode", value: "1 mi+", hint: "Brand Partners ativos" },
    { icon: "package", label: "Produtos no Portfólio", value: "400+", hint: "5 linhas principais" },
    { icon: "dollar", label: "Faturamento Estimado", value: "R$ 1,5 bi+", hint: "Receita Brasil 2024" },
    { icon: "trophy", label: "Convenção Anual", value: "10 mil+", hint: "Pessoas no Hinode Day" },
  ],
  aboutHtml: `
    <p>O <strong>Grupo Hinode</strong> é uma empresa brasileira de marketing multinível fundada em <strong>1988</strong> pelo casal <em>Roberto e Maíra Bom</em> em São Paulo. Começou com uma pequena fábrica de cosméticos no bairro do Brás e cresceu até se tornar uma das maiores e mais reconhecidas empresas de venda direta do Brasil.</p>
    <p>A <strong>Hinode</strong> opera o <strong>Plano Hinode</strong>, um dos planos de carreira mais agressivos do MMN brasileiro, com mais de <strong>1 milhão de Consultores</strong> ativos e presença em <strong>Brasil, Portugal, Estados Unidos, México e Angola</strong>. O portfólio cobre perfumaria, cosméticos, skincare, maquiagem, nutrição esportiva e cuidados pessoais — mais de <strong>400 produtos</strong>.</p>
    <p>Reconhecida pela <strong>convenção anual Hinode Day</strong> (uma das maiores do mundo, com 10 mil+ pessoas), pelos prêmios em <strong>carros, viagens e cheques milionários</strong>, e pela ascensão de líderes brasileiros a posições de topo. Em 2024, o casal fundador anunciou nova fase de internacionalização e digitalização da marca.</p>
  `,
  milestones: [
    { year: "1988", title: "Fundação no Brás, São Paulo", text: "Roberto e Maíra Bom fundam a Hinode com uma pequena fábrica de cosméticos no bairro do Brás, em São Paulo." },
    { year: "2005", title: "Adoção do MMN", text: "A Hinode adota oficialmente o modelo de marketing multinível, criando o Plano Hinode." },
    { year: "2010", title: "Boom da Marca", text: "Crescimento exponencial: Hinode salta de poucos milhares para mais de 200 mil consultores em poucos anos." },
    { year: "2014", title: "Primeira Convenção Internacional", text: "Hinode realiza convenção internacional reunindo líderes de toda a América Latina." },
    { year: "2016", title: "Expansão internacional", text: "Hinode abre operações em Portugal, EUA, México e Angola — virando MMN 100% brasileira com presença em 5 países." },
    { year: "2019", title: "Lançamento da Hinode Academy", text: "Cria plataforma de treinamento online completa para Consultores e Líderes." },
    { year: "2022", title: "Reposicionamento Premium", text: "Hinode reformula identidade visual, abre lojas conceito e foca em produtos premium." },
    { year: "2026", title: "Top MMN do Brasil", text: "Hinode segue como uma das maiores e mais reconhecidas empresas de marketing multinível 100% brasileiras." },
  ],
  productLines: [
    { name: "Perfumaria Hinode", tag: "Fragrâncias Nacionais e Importadas", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Carro-chefe absoluto. Mais de 80 fragrâncias masculinas e femininas, incluindo a linha Premium HND, Traduções (inspiradas em grandes marcas internacionais) e Body Splashes.",
      items: ["HND 71", "HND 7", "Traduções (Linha Inspiração)", "Eclat", "Body Splashes", "Perfumes Infantis"] },
    { name: "H Inspira & Skincare", tag: "Cuidados com a Pele", color: "from-rose-500/15 to-rose-700/5",
      text: "Linha completa de skincare anti-idade, hidratantes e tratamentos faciais.",
      items: ["H Inspira Sérum", "Anti-idade FPS 30", "Hidratante Facial", "Demaquilante", "Máscara Argila"] },
    { name: "Maquiagem Pierre Alexander", tag: "Make Profissional", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Linha de maquiagem Pierre Alexander by Hinode, com bases, batons, paletas e itens para olhos.",
      items: ["Base Líquida HD", "Batom Matte", "Paleta de Sombras", "Máscara de Cílios", "Pó Compacto"] },
    { name: "NextGen Nutrition", tag: "Nutrição Funcional", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Linha de suplementos, shakes substitutos de refeição, termogênicos e barras proteicas.",
      items: ["Shake NextGen", "Termogênico", "Whey Protein", "Colágeno Verisol", "Barras Proteicas"] },
    { name: "Hinode Care & Hair", tag: "Cuidados Pessoais", color: "from-sky-500/15 to-sky-700/5",
      text: "Linha de higiene corporal, capilares e cuidados diários — shampoos, condicionadores, sabonetes, hidratantes.",
      items: ["Shampoo HND Hair", "Hidratante Corporal", "Sabonete Líquido", "Desodorante Aerossol", "Antitranspirante"] },
    { name: "Brand Partner Kits", tag: "Kits & Combos", color: "from-amber-500/15 to-amber-700/5",
      text: "Kits exclusivos com combinações de produtos das diferentes linhas, com descontos especiais para Consultores.",
      items: ["Kit Lançamento", "Kit Família", "Kit Demonstração", "Kit Vendas"] },
  ],
  planTitle: "Plano Hinode — Plano Binário",
  planIntro:
    "O <strong>Plano Hinode</strong> é um plano <strong>binário com matching bonus</strong>, considerado um dos mais agressivos e rentáveis do MMN brasileiro. Premia consultores com <strong>comissões diárias, bônus de equipamento, viagens, carros e cheques milionários</strong>.",
  planRanks: [
    { rank: "Consultor", payout: "30% lucro", text: "Cadastro como Consultor Hinode com kit inicial." },
    { rank: "Consultor Qualificado", payout: "+ Bônus Binário", text: "Patrocina 2 consultores (1 em cada perna do binário)." },
    { rank: "Bronze", payout: "+ Bônus Crescente", text: "Primeira graduação reconhecida pela empresa." },
    { rank: "Prata", payout: "+ Bônus Equipamento", text: "Volume mínimo de equipe consolidado." },
    { rank: "Ouro", payout: "+ Bônus de Carro", text: "Reconhecimento com bônus para compra de veículo." },
    { rank: "Esmeralda / Rubi", payout: "+ Bônus Viagem", text: "Patamares com viagens internacionais e bônus de produção." },
    { rank: "Diamante / Diamante Duplo / Triplo", payout: "+ Bônus Milionário", text: "Patamares de elite, com cheques milionários e participação em pools globais." },
    { rank: "Imperial", payout: "Topo do Plano", text: "Patamar máximo da Hinode, atingido por poucos líderes em toda a história." },
  ],
  pros: [
    "Marca 100% brasileira amplamente reconhecida",
    "Plano binário simples de explicar e duplicar",
    "Convenção Hinode Day com 10 mil+ pessoas (uma das maiores do mundo)",
    "Prêmios em carros, viagens internacionais e bônus milionários",
    "Portfólio diversificado (perfumaria, cosméticos, nutrição)",
    "Plataforma de treinamento Hinode Academy completa",
  ],
  cons: [
    "Plano binário exige equilíbrio entre as pernas",
    "Concorrência forte entre consultores no mesmo mercado",
    "Mudanças históricas no plano de carreira ao longo dos anos",
    "Operação internacional concentrada em poucos países",
    "Modelo binário exige acompanhamento constante de volume",
  ],
  countries: ["🇧🇷 Brasil", "🇵🇹 Portugal", "🇺🇸 EUA", "🇲🇽 México", "🇦🇴 Angola"],
  awards: [
    "Top 5 MMN do Brasil (rankings nacionais)",
    "Empresa do Ano em Vendas Diretas — ABEVD (categorias)",
    "Convenção Hinode Day — Top 10 Maiores Eventos Corporativos da AL",
    "Prêmios em Inovação de Produtos (Perfumaria)",
    "Top of Mind regional em perfumaria de venda direta",
  ],
  certifications: [
    "ANVISA — Boas Práticas de Fabricação",
    "ISO 9001",
    "ABEVD — Associação Brasileira de Vendas Diretas",
    "Selo Vegano em produtos selecionados",
    "Cruelty Free em fórmulas selecionadas",
  ],
  faqs: [
    { q: "A Hinode é uma empresa séria?",
      a: "Sim. A Hinode é uma empresa brasileira fundada em 1988, regulada pela ANVISA e membro da ABEVD (Associação Brasileira de Vendas Diretas), com fábrica própria em São Paulo e operação internacional em 5 países." },
    { q: "Quanto custa o kit Hinode?",
      a: "O kit inicial de Consultor Hinode no Brasil varia entre R$ 150 e R$ 800, dependendo da versão escolhida (Kit Iniciante, Kit Acelerador, Kit Sucesso, Kit Lançamento). Não há mensalidade obrigatória." },
    { q: "Como funciona o Plano Hinode?",
      a: "É um plano binário com matching bonus: o Consultor monta 2 pernas (esquerda e direita) e ganha bônus sobre o volume menor (perna fraca). Há bônus extra por equilíbrio, patrocínio direto, viagens, carros e cheques milionários nas graduações altas." },
    { q: "Quais são os principais produtos da Hinode?",
      a: "O carro-chefe é a perfumaria (HND 71, HND 7, Traduções). Outras linhas: H Inspira (skincare), Pierre Alexander (maquiagem), NextGen (nutrição), Hinode Care (higiene corporal e capilar)." },
    { q: "A Hinode é pirâmide?",
      a: "Não. A Hinode opera com modelo legítimo de venda direta multinível, com produtos físicos vendidos a consumidores finais. É membro da ABEVD, regulada pela ANVISA e tem mais de 35 anos de história comprovada no Brasil." },
    { q: "Em quais países a Hinode opera?",
      a: "A Hinode opera no Brasil (sede), Portugal, Estados Unidos, México e Angola, sendo a maior MMN 100% brasileira com operação internacional." },
    { q: "O que é o Hinode Day?",
      a: "O Hinode Day é a convenção anual da empresa, considerada uma das maiores do MMN no mundo, reunindo mais de 10 mil consultores e líderes em arenas como o Anhembi e o Allianz Parque, com palestras, premiações e lançamento de produtos." },
  ],
  founders: ["Roberto Bom", "Maíra Bom"],
  foundingDate: "1988-01-01",
  foundingLocation: "São Paulo, Brasil",
  employees: 1500,
  alternateNames: ["Grupo Hinode", "Hinode Cosméticos"],
  wikipediaUrl: "https://pt.wikipedia.org/wiki/Hinode",
};

const Hinode = () => <CompanyPremiumPage data={data} />;
export default Hinode;
