import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Longrich",
  slug: "longrich",
  officialUrl: "https://www.longrich.com/",
  domain: "longrich.com",
  seoTitle: "Longrich Bioscience: MMN Chinesa de Cosméticos e Saúde | Top 40 Mundial 2026",
  seoDescription:
    "Longrich Bioscience é uma gigante chinesa de marketing multinível fundada em 1986, com US$ 1,7 bilhão em receita, mais de 6.000 produtos em cosméticos, higiene, saúde e casa, e presença em mais de 190 países.",
  rankingLabel: "TOP 25 MUNDIAL • DSN GLOBAL 100 2026",
  heroHeadlineSuffix: "A Gigante Chinesa de Cosméticos e Wellness",
  heroParagraph:
    "Fundada em 1986 por Xu Zhiwei em Jiangsu (China), a Longrich Bioscience é uma das maiores empresas de venda direta da Ásia, com US$ 1,7 bilhão em receita, mais de 6.000 produtos e presença em mais de 190 países — especialmente forte na África, Sudeste Asiático e mercados emergentes.",
  heroBadges: [
    { label: "39 anos", icon: "calendar" },
    { label: "190+ países", icon: "globe" },
    { label: "6.000+ produtos", icon: "check" },
    { label: "US$ 1,7 bi", icon: "check" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 25", hint: "DSN Global 100" },
    { icon: "calendar", label: "Fundação", value: "1986", hint: "Jiangsu, China" },
    { icon: "map", label: "País de Origem", value: "China 🇨🇳", hint: "Sede em Changzhou, Jiangsu" },
    { icon: "globe", label: "Países", value: "190+", hint: "Ásia, África, Américas, Europa" },
    { icon: "users", label: "Distribuidores", value: "1 milhão+", hint: "Rede global ativa" },
    { icon: "package", label: "Produtos", value: "6.000+", hint: "Portfólio mais amplo do MMN mundial" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 1,7 bi", hint: "Fonte: DSN Global 100" },
    { icon: "factory", label: "Fábricas próprias", value: "6", hint: "China — automação de ponta" },
  ],
  aboutHtml: `
    <p>A <strong>Longrich Bioscience Co., Ltd.</strong> é uma multinacional chinesa fundada em <strong>1986</strong> por <strong>Xu Zhiwei</strong>, com sede em <strong>Changzhou, província de Jiangsu</strong>. É uma das maiores empresas de marketing multinível da Ásia e uma das poucas chinesas com forte penetração na África e mercados emergentes.</p>
    <p>Com portfólio de <strong>mais de 6.000 produtos</strong> em cosméticos, cuidados pessoais, saúde, wellness, produtos para casa e alimentação funcional, a Longrich é conhecida pela combinação de <strong>tecnologia farmacêutica chinesa</strong>, ingredientes bioativos e preços competitivos que a tornaram líder de mercado na Nigéria, Gana, Filipinas e outros países emergentes.</p>
    <p>Com receita de <strong>US$ 1,7 bilhão em 2025</strong> e presença em <strong>mais de 190 países</strong>, ocupa o <strong>Top 25 do DSN Global 100 2026</strong>. Investe pesado em pesquisa — mantém 6 institutos de P&D e mais de 300 patentes registradas.</p>
  `,
  timelineTitle: "Da farmacêutica chinesa à gigante global do MMN",
  milestones: [
    { year: "1986", title: "Fundação por Xu Zhiwei", text: "Nasce como empresa farmacêutica em Changzhou, Jiangsu." },
    { year: "1994", title: "Entrada no MMN", text: "Adota modelo de marketing direto para distribuição de cosméticos." },
    { year: "2003", title: "Expansão asiática", text: "Chegada às Filipinas, Malásia, Indonésia e Vietnã." },
    { year: "2007", title: "Chegada à África", text: "Abre operação na Nigéria — hoje o maior mercado da empresa." },
    { year: "2012", title: "US$ 500 mi", text: "Atinge meio bilhão de dólares em receita anual." },
    { year: "2017", title: "US$ 1 bi", text: "Cruza a marca de US$ 1 bilhão em faturamento global." },
    { year: "2020", title: "Expansão para as Américas", text: "Operações no Brasil, México, Colômbia e Peru." },
    { year: "2026", title: "Top 25 mundial", text: "US$ 1,7 bilhão, presença em 190+ países e liderança em mercados emergentes." },
  ],
  productsIntro:
    "Portfólio gigante com <strong>6.000+ produtos</strong> em <strong>cosméticos, saúde, wellness, higiene, alimentos funcionais e produtos para casa</strong>. Marca reconhecida pelo <strong>absorvente higiênico com nanoprata</strong> e cremes com ginseng chinês.",
  productLines: [
    { name: "Cosméticos & Skincare", tag: "Categoria líder", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linhas de skincare, maquiagem, cuidados anti-idade com ingredientes bioativos chineses.",
      items: ["Longrich Perfume", "Skincare Anti-Age", "Makeup Line", "Bio White"] },
    { name: "Higiene Feminina", tag: "Best-seller mundial", color: "from-rose-500/15 to-rose-700/5",
      text: "Absorventes com nanoprata e íons negativos — best-seller mundial da marca com milhões vendidos.",
      items: ["Sanitary Napkins Day", "Sanitary Napkins Night", "Pantyliners", "Baby Diapers"] },
    { name: "Saúde & Wellness", tag: "Suplementos", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Suplementos com ginseng, cordyceps, chá verde e ervas da medicina tradicional chinesa.",
      items: ["Ginseng Tea", "Cordyceps Capsules", "Reishi Extract", "Berry Oil"] },
    { name: "Casa & Alimentação", tag: "Complementar", color: "from-amber-500/15 to-amber-700/5",
      text: "Purificadores de água, produtos de limpeza ecológicos, café e alimentos funcionais.",
      items: ["Water Purifier", "Household Cleaner", "Longrich Coffee", "Functional Foods"] },
  ],
  planTitle: "Plano de Compensação Longrich (Uni-Binário Híbrido)",
  planIntro:
    "Modelo <strong>uni-binário</strong> com bônus de patrocínio direto, comissão binária diária, Matching Bonus, bônus de liderança, pool internacional e incentivos como carro (Longrich Car Fund) e casa (House Fund) para os top ranks.",
  planRanks: [
    { rank: "Distribuidor", payout: "25% desconto", text: "Registro básico — desconto de atacado em todos os produtos." },
    { rank: "Star 1 / Star 2", payout: "Bônus binário 8-12%", text: "Ativa PV mínimo mensal e começa a receber comissão diária." },
    { rank: "Silver Executive", payout: "+ Matching 20%", text: "3 pernas ativas — Matching Bonus dos frontlines." },
    { rank: "Gold / Ruby", payout: "+ Bônus de Liderança", text: "Múltiplas equipes qualificadas — participa do pool 2%." },
    { rank: "Diamond / Crown Diamond", payout: "+ Car Fund + House Fund", text: "Qualificação para bônus mensal de carro (US$ 500-3.000) e casa." },
    { rank: "President / International President", payout: "Pool internacional", text: "Elite mundial — bônus quadrimestrais em 6/7 dígitos." },
  ],
  pros: [
    "Portfólio gigantesco (6.000+ produtos) — atende todos os perfis",
    "Preços competitivos vs concorrência americana/europeia",
    "Bônus binário pago diariamente (raro no setor)",
    "Forte presença na África e mercados emergentes",
    "Kit inicial acessível a partir de US$ 30",
    "Empresa consolidada com 39 anos e US$ 1,7 bi/ano",
  ],
  cons: [
    "Operação no Brasil ainda em consolidação",
    "Marca menos conhecida na América Latina",
    "Concorrência forte com Herbalife, Amway e Natura",
    "Ativação mensal exigida para qualificar bônus",
    "Materiais de treinamento em português ainda limitados",
  ],
  presenceIntro:
    "A Longrich opera em <strong>mais de 190 países</strong> — a maior amplitude geográfica do MMN mundial. Forte especialmente na <strong>África (Nigéria, Gana, Camarões, Quênia)</strong>, <strong>Sudeste Asiático</strong> e mercados emergentes das Américas.",
  countries: [
    "🇨🇳 China", "🇭🇰 Hong Kong", "🇳🇬 Nigéria", "🇬🇭 Gana", "🇰🇪 Quênia",
    "🇺🇬 Uganda", "🇨🇲 Camarões", "🇨🇮 Costa do Marfim", "🇿🇦 África do Sul", "🇪🇬 Egito",
    "🇹🇿 Tanzânia", "🇷🇼 Ruanda", "🇸🇳 Senegal", "🇵🇭 Filipinas", "🇲🇾 Malásia",
    "🇮🇩 Indonésia", "🇹🇭 Tailândia", "🇻🇳 Vietnã", "🇸🇬 Singapura", "🇮🇳 Índia",
    "🇵🇰 Paquistão", "🇧🇩 Bangladesh", "🇺🇸 EUA", "🇧🇷 Brasil", "🇲🇽 México",
    "🇨🇴 Colômbia", "🇵🇪 Peru", "🇬🇧 Reino Unido", "🇩🇪 Alemanha", "🇫🇷 França",
  ],
  awards: [
    "DSN Global 100 — Top 25 (2026)",
    "China Direct Selling Association — Top 10",
    "Best Enterprise in Africa Direct Selling",
    "Nigéria: Prêmio Empresa do Ano em Cosméticos (múltiplos anos)",
    "300+ patentes internacionais registradas",
  ],
  certifications: [
    "GMP (Good Manufacturing Practice)",
    "ISO 9001 / ISO 14001",
    "SGS Certified",
    "CE (Europa)",
    "FDA China Registered",
    "Halal Certified (linhas selecionadas)",
  ],
  faqs: [
    { q: "O que é a Longrich?",
      a: "É uma multinacional chinesa de marketing multinível fundada em 1986 por Xu Zhiwei em Changzhou (China), com foco em cosméticos, higiene, saúde e produtos para casa. É a maior empresa de MMN da China com presença em 190+ países." },
    { q: "Quanto fatura a Longrich em 2026?",
      a: "A Longrich faturou US$ 1,7 bilhão em 2025, ocupando o Top 25 do ranking Direct Selling News Global 100 2026 — uma das gigantes do setor mundial." },
    { q: "A Longrich opera no Brasil?",
      a: "Sim, a Longrich tem operação oficial no Brasil desde 2020, com escritório e logística local. A comunidade brasileira ainda está em fase de consolidação em comparação com a nigeriana e filipina." },
    { q: "Qual é o produto mais vendido da Longrich?",
      a: "O absorvente higiênico com nanoprata e íons negativos é o best-seller mundial da marca, seguido pelos perfumes, cremes anti-idade com ginseng chinês e a linha de suplementos com cordyceps." },
    { q: "Como funciona o plano de compensação da Longrich?",
      a: "É um plano uni-binário híbrido: você constrói duas pernas de rede e recebe comissão binária DIÁRIA (raro no setor), além de Matching Bonus de 20% dos frontlines, Car Fund, House Fund e pool internacional para top ranks." },
    { q: "Quanto custa começar na Longrich?",
      a: "O kit básico custa a partir de US$ 30 (~R$ 155). Kits maiores (Silver, Gold, Platinum) variam de US$ 200 a US$ 2.000 e desbloqueiam mais bônus de rápida qualificação." },
    { q: "Longrich é pirâmide financeira?",
      a: "Não. A Longrich é uma empresa de MMN legítima com 39 anos de mercado, 6 fábricas próprias na China, US$ 1,7 bi/ano em receita e produtos reais vendidos ao consumidor final. Está no ranking DSN Global 100 há mais de uma década." },
    { q: "Por que a Longrich é tão forte na África?",
      a: "A empresa entrou cedo em mercados africanos com preços acessíveis, produtos adaptados (perfumes, cosméticos, higiene feminina) e plano de compensação atrativo em moedas locais. Hoje é líder de mercado em vários países africanos, incluindo Nigéria e Gana." },
    { q: "Quantos produtos a Longrich tem?",
      a: "Mais de 6.000 produtos em cosméticos, skincare, higiene, suplementos, wellness, produtos para casa, alimentação funcional e cuidados infantis — o portfólio mais amplo do MMN mundial." },
    { q: "Vale a pena entrar na Longrich em 2026?",
      a: "Sim, especialmente para quem tem contatos internacionais (África, Ásia) ou quer trabalhar com portfólio amplo a preços competitivos. É uma das empresas mais sólidas do setor com pagamento binário diário e forte crescimento global." },
  ],
  founders: ["Xu Zhiwei"],
  foundingDate: "1986-01-01",
  foundingLocation: "Changzhou, Jiangsu, China",
  employees: 8000,
  alternateNames: ["Longrich Bioscience", "隆力奇"],
};

const Longrich = () => <CompanyPremiumPage data={data} />;
export default Longrich;
