import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Mary Kay",
  slug: "mary-kay",
  officialUrl: "https://www.marykay.com.br/",
  domain: "marykay.com",
  seoTitle: "Mary Kay: A Gigante da Cosmética em Venda Direta | Carro Rosa | 2026",
  seoDescription:
    "Mary Kay é uma das maiores empresas de cosméticos do mundo em venda direta com US$ 2,8 bi de receita. Conheça a história, produtos TimeWise, plano de carreira e o icônico Cadillac Rosa.",
  rankingLabel: "TOP 10 MUNDIAL • BUSINESS FOR HOME 2026",
  heroHeadlineSuffix: "A Lenda dos Cosméticos e do Cadillac Rosa",
  heroParagraph:
    "Fundada em 1963 por Mary Kay Ash em Dallas, Texas, a Mary Kay é uma das mais icônicas empresas de cosméticos em venda direta do mundo, com mais de 3 milhões de Consultoras Independentes em 35+ países e US$ 2,8 bilhões em receita anual.",
  heroBadges: [
    { label: "Receita verificada", icon: "check" },
    { label: "60+ anos", icon: "calendar" },
    { label: "35+ países", icon: "globe" },
    { label: "3 mi de consultoras", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 10", hint: "Líder em cosméticos por venda direta" },
    { icon: "calendar", label: "Fundação", value: "1963", hint: "60+ anos de história" },
    { icon: "map", label: "País de Origem", value: "EUA 🇺🇸", hint: "Dallas, Texas" },
    { icon: "globe", label: "Países & Territórios", value: "35+", hint: "Operação em 5 continentes" },
    { icon: "users", label: "Consultoras de Beleza", value: "3 mi+", hint: "Maior força de vendas feminina do mundo" },
    { icon: "package", label: "Produtos no Portfólio", value: "200+", hint: "Skincare, maquiagem e fragrâncias" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 2,8 bi", hint: "Fonte: Business For Home" },
    { icon: "trophy", label: "Cadillacs Rosa Dados", value: "100.000+", hint: "Maior frota de carros de premiação do mundo" },
  ],
  aboutHtml: `
    <p>A <strong>Mary Kay Inc.</strong> é uma empresa americana de cosméticos por venda direta fundada em <strong>13 de setembro de 1963</strong> por <em>Mary Kay Ash</em>, em Dallas, Texas. Criada com a missão de <strong>"enriquecer a vida das mulheres ao redor do mundo"</strong>, é hoje uma das maiores e mais admiradas empresas femininas de todos os tempos.</p>
    <p>A <strong>Mary Kay</strong> é a casa do icônico <strong>Cadillac Rosa</strong>, dado como prêmio a líderes desde 1969 — mais de <strong>100.000 carros já entregues</strong>. Fatura <strong>US$ 2,8 bilhões anuais</strong>, mantém mais de <strong>3 milhões de Consultoras de Beleza</strong> em mais de <strong>35 países</strong> e ocupa o <strong>Top 10 mundial</strong> no ranking Business For Home 2026.</p>
    <p>É uma empresa <strong>100% familiar</strong>, sem capital aberto, com sede em Addison, Texas. Mantém o instituto <strong>Mary Kay Ash Foundation</strong> (combate ao câncer e à violência doméstica), centro próprio de P&D, fábrica em Dallas e laboratórios em Xangai. Marcas-ícone: <strong>TimeWise, Botanical Effects, Clear Proof, Lash Love</strong> e a icônica <strong>Maquiagem Mineral</strong>.</p>
  `,
  milestones: [
    { year: "1963", title: "Fundação por Mary Kay Ash", text: "Mary Kay Ash, com US$ 5.000 de economia, funda a Beauty by Mary Kay em Dallas, criando o lendário 'Princípio da Regra Áurea' e a filosofia 'God first, family second, career third'." },
    { year: "1969", title: "Primeiro Cadillac Rosa", text: "Mary Kay encomenda o primeiro Cadillac na cor 'Mary Kay Pink' como prêmio para 5 líderes — nasce o ícone que viraria sinônimo da empresa." },
    { year: "1971", title: "Expansão internacional", text: "Primeira operação fora dos EUA, na Austrália. Início da expansão global." },
    { year: "1986", title: "Compra de capital", text: "Os Ash recompram todas as ações da empresa, voltando a ser 100% familiar." },
    { year: "1995", title: "Entrada no Brasil", text: "A Mary Kay desembarca no Brasil e em poucos anos vira um dos maiores mercados globais." },
    { year: "2001", title: "Falecimento de Mary Kay Ash", text: "Mary Kay Ash falece aos 83 anos, deixando um império que continua sendo dirigido pela família." },
    { year: "2003", title: "Lançamento da TimeWise", text: "Lançamento da linha TimeWise, anti-idade que viraria o carro-chefe da empresa." },
    { year: "2014", title: "Expansão para a Índia", text: "Mary Kay India abre operação com forte crescimento no mercado feminino emergente." },
    { year: "2024", title: "Reformulação TimeWise 4D Plus", text: "Lançamento da nova geração TimeWise 4D Plus, com tecnologia exclusiva multidimensional anti-idade." },
    { year: "2026", title: "Top 10 Mundial", text: "Mary Kay mantém posição Top 10 no ranking Business For Home 2026 com US$ 2,8 bilhões em receita." },
  ],
  productsIntro:
    "Mais de <strong>200 produtos</strong> distribuídos em <strong>10+ linhas</strong>, com forte investimento próprio em P&D (mais de 2.700 patentes registradas em todo o mundo).",
  productLines: [
    { name: "TimeWise 4D Plus", tag: "Anti-idade Premium", color: "from-rose-500/15 to-rose-700/5",
      text: "Linha anti-idade carro-chefe da Mary Kay, com tecnologia 4D Plus que combate as 4 dimensões do envelhecimento: linhas, firmeza, manchas e luminosidade. Mais de 200 prêmios internacionais.",
      items: ["Day Cream FPS 30", "Night Cream", "Eye Cream", "Sérum Vitamina C+E", "Esfoliante 3-em-1", "Loção Tonificante"] },
    { name: "Botanical Effects", tag: "Skincare Vegano", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Linha 100% vegana e livre de parabenos, com fórmulas para 3 tipos de pele (seca, mista e oleosa). Formulada com extratos botânicos.",
      items: ["Limpeza", "Hidratante", "Máscara Calmante", "Sérum Hidratante"] },
    { name: "Clear Proof", tag: "Tratamento Antiacne", color: "from-sky-500/15 to-sky-700/5",
      text: "Sistema completo de tratamento da acne com ácido salicílico clinicamente comprovado, em 3 passos. Aprovado por dermatologistas.",
      items: ["Gel de Limpeza", "Loção Anti-Imperfeição", "Hidratante Oil-Free", "Máscara de Argila"] },
    { name: "Lash Love & Olhos", tag: "Maquiagem para Olhos", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Máscaras de cílios premiadas (Lash Love, Lash Intensity, Ultimate), delineadores, sombras minerais e paletas exclusivas.",
      items: ["Lash Love", "Lash Intensity", "Sombras Minerais", "Delineador Líquido", "Lápis para Olhos"] },
    { name: "Linha Lábios & Base", tag: "Maquiagem Facial", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Bases minerais com mais de 30 tons inclusivos, batons True Dimensions com vitamina C, gloss NouriShine Plus e contornos prontos.",
      items: ["Base Mineral CC", "True Dimensions Batom", "NouriShine Plus Gloss", "Pó Compacto", "Blush Cremoso"] },
    { name: "Linha Body & Spa", tag: "Cuidados Corporais & SPA", color: "from-amber-500/15 to-amber-700/5",
      text: "Linha completa de cuidado corporal com fragrâncias exclusivas, esfoliantes, hidratantes e óleos corporais — alguns inspirados em SPAs de luxo.",
      items: ["Satin Hands", "Satin Body", "Body Mist", "Óleo Corporal", "Hand & Décolleté"] },
  ],
  planTitle: "Plano de Carreira Mary Kay — Lucro de 40% + Bônus",
  planIntro:
    "A Mary Kay opera com <strong>lucro de 40% sobre todos os produtos</strong> e bônus progressivos de equipe a partir do nível Estrela Vermelha. É um dos planos mais lucrativos do setor, com prêmios em <strong>joias, viagens, Mont Blanc e o lendário Cadillac Rosa</strong>.",
  planRanks: [
    { rank: "Consultora de Beleza Independente", payout: "40% lucro", text: "Cadastro com a Sessão de Lançamento. Compra com 40% de desconto e revende com lucro." },
    { rank: "Estrela Vermelha", payout: "40% + 4% bônus", text: "Recruta 1-2 consultoras qualificadas. Primeiro nível de equipe." },
    { rank: "Líder de Equipe", payout: "+ 4-9% override", text: "3-7 consultoras ativas em primeira linha." },
    { rank: "Futura Diretora", payout: "+ Bônus mensais", text: "8-9 consultoras qualificadas. Pré-requisito para diretoria." },
    { rank: "Diretora em Qualificação", payout: "+ 13% override", text: "10+ consultoras na 1ª linha, em fase final para Diretora." },
    { rank: "Diretora Independente", payout: "+ 13% e Bônus de Carro", text: "Atinge metas como Diretora — pode ganhar o Cadillac Rosa após qualificação anual." },
    { rank: "Diretora Sênior / Executiva", payout: "+ Comissão de Diretoria", text: "Forma novas diretoras na sua área — comissão sobre toda a estrutura." },
    { rank: "Diretora Nacional", payout: "Topo do Plano", text: "Topo absoluto da carreira Mary Kay — ganhos seis ou sete dígitos anuais." },
  ],
  pros: [
    "Lucro fixo e alto de 40% sobre todos os produtos (um dos maiores do setor)",
    "Plano de carreira icônico com Cadillac Rosa, joias e viagens internacionais",
    "Empresa centenária focada 100% em empoderamento feminino",
    "Treinamento estruturado em todas as etapas (Sessões, Seminários, Convenções)",
    "Garantia de 100% de satisfação para a cliente",
    "Marca consolidada com forte apelo emocional e fidelidade",
  ],
  cons: [
    "Investimento inicial em estoque pode ser alto",
    "Estoque próprio é parte do modelo (alguns países permitem sem estoque)",
    "Programa do Cadillac Rosa exige qualificação contínua para manter",
    "Plano de carreira mais tradicional (não binário)",
    "Concorrência forte de marcas brasileiras como Natura e Boticário no Brasil",
  ],
  countries: [
    "🇺🇸 EUA", "🇨🇦 Canadá", "🇲🇽 México", "🇧🇷 Brasil", "🇦🇷 Argentina", "🇨🇴 Colômbia",
    "🇨🇱 Chile", "🇵🇪 Peru", "🇬🇧 Reino Unido", "🇩🇪 Alemanha", "🇫🇷 França", "🇪🇸 Espanha",
    "🇷🇺 Rússia", "🇰🇿 Cazaquistão", "🇨🇿 Tchéquia", "🇸🇰 Eslováquia", "🇵🇱 Polônia", "🇺🇦 Ucrânia",
    "🇨🇳 China", "🇭🇰 Hong Kong", "🇹🇼 Taiwan", "🇰🇷 Coreia do Sul", "🇮🇳 Índia", "🇲🇾 Malásia",
    "🇵🇭 Filipinas", "🇹🇭 Tailândia", "🇻🇳 Vietnã", "🇸🇬 Singapura", "🇦🇺 Austrália",
  ],
  awards: [
    "Top 10 Direct Selling News Global 100 — 2026",
    "Most Powerful Women in Business — Forbes (Mary Kay Ash)",
    "America's Greatest Business Stories (Time Magazine)",
    "Direct Selling Association Hall of Fame",
    "Stevie Awards for Women in Business",
    "Forbes World's Best Employers",
  ],
  certifications: [
    "Leaping Bunny (Cruelty Free)",
    "Vegan Society (linhas selecionadas)",
    "ISO 9001 (Gestão da Qualidade)",
    "ISO 14001 (Gestão Ambiental)",
    "USDA Organic (linhas selecionadas)",
    "Boas Práticas ANVISA (operação Brasil)",
  ],
  faqs: [
    { q: "Quanto custa o kit de início Mary Kay?",
      a: "O Kit Vitrine de início Mary Kay no Brasil custa entre R$ 350 e R$ 550 conforme a versão (Kit Iniciante ou Kit Sucesso), contendo produtos para demonstração, catálogo e material de treinamento. A renovação anual é simbólica." },
    { q: "Quanto a Consultora Mary Kay ganha?",
      a: "A Consultora Mary Kay tem lucro fixo de 40% sobre todos os produtos. Líderes de equipe ganham bônus adicionais de 4% a 13% sobre a produção da equipe, e Diretoras qualificadas podem ganhar o Cadillac Rosa, joias, viagens internacionais e bônus mensais em dinheiro." },
    { q: "A Mary Kay é uma empresa séria ou pirâmide?",
      a: "A Mary Kay é uma empresa familiar americana com mais de 60 anos de história, presença em 35+ países e mais de US$ 2,8 bilhões de faturamento. É membro do Direct Selling Association (DSA) e da ABEVD no Brasil. Não é pirâmide — opera com modelo legítimo de venda direta com produto consumível." },
    { q: "Quais são os principais produtos da Mary Kay?",
      a: "Os carros-chefe são a linha anti-idade TimeWise 4D Plus, skincare vegano Botanical Effects, tratamento de acne Clear Proof, maquiagem de olhos Lash Love, bases minerais inclusivas e a linha corporal Satin Hands e Satin Body." },
    { q: "Como funciona o programa do Cadillac Rosa?",
      a: "Diretoras Independentes que atingem metas de produção de equipe ganham um Cadillac Rosa novo (ou carro premium equivalente) por 2 anos, pago pela Mary Kay. É preciso manter qualificação trimestral para continuar com o carro. Já foram entregues mais de 100.000 Cadillacs Rosa em todo o mundo." },
    { q: "Em quantos países a Mary Kay opera?",
      a: "A Mary Kay opera em mais de 35 países, com presença nos 5 continentes. Os maiores mercados são EUA, China, Rússia, México e Brasil." },
    { q: "Mary Kay testa em animais?",
      a: "Não. A Mary Kay é certificada Leaping Bunny e tem sido pioneira global em alternativas a testes em animais desde 1989, investindo mais de US$ 5 milhões em pesquisa de métodos alternativos." },
    { q: "Qual a diferença da Mary Kay para outras marcas de cosméticos?",
      a: "A Mary Kay combina cosméticos premium com modelo de empreendedorismo feminino, plano de carreira icônico (Cadillac Rosa), filosofia 'God first, family second, career third' e garantia de satisfação 100% para a cliente." },
  ],
  founders: ["Mary Kay Ash"],
  foundingDate: "1963-09-13",
  foundingLocation: "Dallas, Texas, EUA",
  employees: 5000,
  alternateNames: ["Mary Kay Inc.", "Mary Kay Cosmetics"],
  wikipediaUrl: "https://pt.wikipedia.org/wiki/Mary_Kay",
};

const MaryKay = () => <CompanyPremiumPage data={data} />;
export default MaryKay;
