import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Natura",
  slug: "natura",
  officialUrl: "https://www.natura.com.br/",
  domain: "naturaeco.com",
  seoTitle: "Natura &Co: A Maior Empresa de Cosméticos do Brasil | Ranking 2026",
  seoDescription:
    "Natura é a maior empresa brasileira de cosméticos e a #4 do ranking mundial de venda direta com US$ 3,8 bi. Conheça produtos Ekos, Tododia, Chronos, plano de consultoria e a história da Natura &Co.",
  rankingLabel: "TOP 5 MUNDIAL • MAIOR DO BRASIL • BUSINESS FOR HOME 2026",
  heroHeadlineSuffix: "A Cosmética Brasileira que Conquistou o Mundo",
  heroParagraph:
    "Fundada em 1969 em São Paulo, a Natura é a maior empresa brasileira de cosméticos e a maior multinacional latino-americana de venda direta, com mais de 5,4 milhões de Consultoras Natura, presença em 100+ países e US$ 3,8 bilhões em receita anual.",
  heroBadges: [
    { label: "Certificada B Corp", icon: "check" },
    { label: "55+ anos", icon: "calendar" },
    { label: "100+ países", icon: "globe" },
    { label: "5,4 mi de consultoras", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 5", hint: "Maior empresa brasileira do setor" },
    { icon: "calendar", label: "Fundação", value: "1969", hint: "55+ anos de história" },
    { icon: "map", label: "País de Origem", value: "Brasil 🇧🇷", hint: "Cajamar, São Paulo" },
    { icon: "globe", label: "Países & Territórios", value: "100+", hint: "Operação global via Natura &Co" },
    { icon: "users", label: "Consultoras Natura", value: "5,4 mi+", hint: "Maior rede de vendas do Brasil" },
    { icon: "package", label: "Produtos no Portfólio", value: "1.500+", hint: "Cosméticos, perfumaria e cuidados" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 3,8 bi", hint: "Fonte: Business For Home" },
    { icon: "leaf", label: "Bioma Amazônia", value: "40+ insumos", hint: "Da sociobiodiversidade brasileira" },
  ],
  aboutHtml: `
    <p>A <strong>Natura Cosméticos</strong> é uma multinacional brasileira fundada em <strong>1969</strong> por <em>Luiz Seabra</em>, em São Paulo, com a filosofia <strong>"Bem Estar Bem"</strong>. É a maior empresa de cosméticos do Brasil e a maior multinacional latino-americana de venda direta.</p>
    <p>Listada na B3 (NATU3) e controladora do grupo <strong>Natura &Co</strong> (que já reuniu marcas como Avon, The Body Shop e Aesop), a Natura fatura <strong>US$ 3,8 bilhões anuais</strong> e mantém uma rede de mais de <strong>5,4 milhões de Consultoras de Beleza</strong>, sendo a maior força de vendas diretas do Brasil.</p>
    <p>Pioneira mundial em <strong>sustentabilidade corporativa</strong>, é a primeira multinacional listada em bolsa a obter a certificação <strong>B Corp</strong>. Utiliza mais de <strong>40 ativos da sociobiodiversidade da Amazônia</strong>, mantém o Programa Amazônia e tem como linhas-ícone <strong>Ekos, Tododia, Chronos, Una, Kaiak, Humor</strong> e o lendário sabonete <strong>Erva Doce</strong>.</p>
  `,
  timelineTitle: "55 anos da pequena loja em São Paulo à multinacional global",
  milestones: [
    { year: "1969", title: "Fundação em São Paulo", text: "Luiz Seabra abre a primeira lojinha Natura na Rua Oscar Freire, com poucos produtos artesanais de cosmetologia." },
    { year: "1974", title: "Modelo de Venda Direta", text: "A Natura adota o modelo de venda direta por Consultoras, revolucionando o mercado brasileiro de cosméticos." },
    { year: "1983", title: "Refil ecológico", text: "Pioneira mundial em refis, lança o primeiro sistema de refis para reduzir consumo de embalagens em até 70%." },
    { year: "1992", title: "Linha Chronos", text: "Lançamento de Chronos, primeira linha brasileira anti-idade premium, com pesquisas próprias em ciência da pele." },
    { year: "2000", title: "Linha Ekos", text: "Ekos é lançada, levando ativos da sociobiodiversidade amazônica para todo o Brasil — castanha, cacau, cupuaçu, andiroba, breu-branco." },
    { year: "2004", title: "IPO na Bovespa", text: "Natura abre capital na Bovespa (atual B3) com IPO recorde, valorizando 33% no primeiro dia." },
    { year: "2014", title: "Primeira B Corp listada em bolsa", text: "Natura se torna a primeira multinacional listada em bolsa do mundo a obter a certificação B Corp." },
    { year: "2017", title: "Aquisição da The Body Shop", text: "Natura adquire a britânica The Body Shop por € 1 bilhão, criando o grupo Natura &Co." },
    { year: "2020", title: "Aquisição da Avon", text: "Conclusão da fusão com Avon, criando o 4º maior grupo mundial de beleza pure-play." },
    { year: "2026", title: "Reorganização Natura &Co", text: "Após desinvestir de Aesop e The Body Shop, Natura &Co foca em Natura e Avon na América Latina, mantendo posição no Top 5 global." },
  ],
  productsIntro:
    "Mais de <strong>1.500 produtos</strong> distribuídos em <strong>15+ linhas</strong>, com forte uso de ativos da biodiversidade brasileira e tecnologia própria de cosmetologia.",
  productLines: [
    { name: "Ekos", tag: "Sociobiodiversidade Amazônica", color: "from-emerald-500/15 to-emerald-700/5",
      text: "A linha-ícone da Natura, com fragrâncias e cosméticos formulados com ativos da Amazônia — castanha, açaí, cupuaçu, andiroba, breu-branco — em parceria com comunidades extrativistas.",
      items: ["Castanha", "Cacau", "Cupuaçu", "Açaí", "Andiroba", "Breu-Branco", "Pitanga", "Maracujá"] },
    { name: "Chronos", tag: "Anti-idade Premium", color: "from-rose-500/15 to-rose-700/5",
      text: "Linha anti-idade #1 do Brasil, com tecnologia patenteada Hyalu Booster e divisão por décadas de vida (30+, 45+, 60+, 70+).",
      items: ["Chronos 30+", "45+", "60+", "70+", "Sérum Hyalu Booster", "Olhos & Lábios", "Filtro Solar FPS"] },
    { name: "Tododia", tag: "Cuidados Diários", color: "from-amber-500/15 to-amber-700/5",
      text: "A linha mais democrática da Natura: hidratantes corporais, sabonetes e desodorantes para uso diário, com fragrâncias como Algodão, Maçã & Lichia e Ameixa.",
      items: ["Hidratante Algodão", "Sabonete Líquido", "Desodorante", "Body Splash", "Óleo Corporal"] },
    { name: "Kaiak & Humor", tag: "Perfumaria Brasileira", color: "from-sky-500/15 to-sky-700/5",
      text: "Perfumaria contemporânea brasileira premiada internacionalmente. Kaiak é o perfume mais vendido do Brasil há décadas; Humor é referência em fragrâncias femininas modernas.",
      items: ["Kaiak Original", "Kaiak Aero", "Humor 1, 2, 3...", "Essencial Exclusivo", "Una Artisan"] },
    { name: "Mamãe e Bebê", tag: "Cuidados Infantis", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linha completa para bebês com fórmulas hipoalergênicas, dermatologicamente testadas e aprovadas pela Sociedade Brasileira de Pediatria.",
      items: ["Shampoo Suave", "Sabonete", "Hidratante", "Colônia Bebê", "Óleo de Massagem"] },
    { name: "Maquiagem (Una, Faces, Aquarela)", tag: "Make Brasileira", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Linhas de maquiagem com tons inclusivos para a pele brasileira (40+ tons de base), formulações veganas e parcerias com maquiadores celebridades.",
      items: ["Una Base", "Faces Batom", "Aquarela Linha Jovem", "Lipstick Mate", "Sombras Naturais"] },
  ],
  planTitle: "Plano de Consultoria Natura — Ciclo de 21 Dias",
  planIntro:
    "A Natura opera um modelo único de <strong>venda direta single-level com lucros progressivos</strong>, com ciclos de 21 dias e <strong>margem de até 50%</strong> sobre os produtos. Há também o programa de <strong>Consultoria de Beleza Digital (CND)</strong> com loja online própria.",
  planRanks: [
    { rank: "Consultora Natura", payout: "Até 30% lucro", text: "Cadastro gratuito. Compra com desconto e revende com lucro." },
    { rank: "Consultora Qualificada", payout: "Até 35% lucro", text: "Atinge volume mínimo de pedidos no ciclo." },
    { rank: "CND - Consultora Natura Digital", payout: "+ Comissão online", text: "Loja virtual própria com comissão sobre vendas feitas pelo link." },
    { rank: "Bronze", payout: "+ 1% Rede", text: "Inicia formação de rede de consultoras indicadas." },
    { rank: "Prata", payout: "+ 2% Rede", text: "Crescimento qualificado de equipe direta." },
    { rank: "Ouro", payout: "+ 3% Rede", text: "Liderança consolidada com várias consultoras ativas." },
    { rank: "Diamante", payout: "+ Bônus Liderança", text: "Estrutura grande com sub-líderes formados." },
    { rank: "Master", payout: "Topo do Plano", text: "Reconhecimento máximo, com bônus, viagens e Top Líder Natura." },
  ],
  pros: [
    "Maior empresa brasileira de cosméticos e venda direta",
    "Cadastro gratuito como Consultora",
    "Marca amada e reconhecida em todo o Brasil",
    "Ciclo curto de 21 dias com reposição constante de novidades",
    "Sustentabilidade real (B Corp) e produtos com selo vegano",
    "Plataforma digital robusta (CND) com loja virtual própria",
  ],
  cons: [
    "Margem menor que MMNs internacionais focados em multinível",
    "Competição interna alta em grandes centros urbanos",
    "Plano de carreira de rede mais simples que de outras grandes MMNs",
    "Vendas online competem com o sistema porta a porta tradicional",
    "Logística depende do ciclo de 21 dias (sem entrega imediata)",
  ],
  presenceIntro:
    "Principais mercados: <strong>Brasil, Argentina, México, Chile, Colômbia, Peru, EUA e Europa</strong> (via marca Natura) e dezenas de outros via Avon (também controlada).",
  countries: [
    "🇧🇷 Brasil", "🇦🇷 Argentina", "🇨🇱 Chile", "🇵🇪 Peru", "🇨🇴 Colômbia", "🇲🇽 México",
    "🇺🇾 Uruguai", "🇵🇾 Paraguai", "🇧🇴 Bolívia", "🇪🇨 Equador", "🇺🇸 EUA", "🇨🇦 Canadá",
    "🇫🇷 França", "🇬🇧 Reino Unido", "🇮🇹 Itália", "🇩🇪 Alemanha", "🇪🇸 Espanha", "🇵🇹 Portugal",
    "🇲🇾 Malásia", "🇮🇩 Indonésia", "🇵🇭 Filipinas", "🇿🇦 África do Sul", "🇦🇺 Austrália",
  ],
  awards: [
    "Top 5 Direct Selling News Global 100 — 2026",
    "Empresa Mais Sustentável do Mundo — Corporate Knights",
    "Primeira multinacional listada em bolsa certificada B Corp",
    "Prêmio ABRE de Embalagem (várias edições)",
    "Forbes World's Best Employers",
    "Prêmio Whole Planet Foundation (Amazônia)",
    "Top of Mind de Cosméticos no Brasil há mais de 20 anos consecutivos",
  ],
  certifications: [
    "B Corporation (desde 2014)",
    "Carbono Neutro desde 2007",
    "Cruelty Free (PETA) — Empresa Pioneira no Brasil",
    "ISO 14001 (Gestão Ambiental)",
    "ISO 9001 (Gestão da Qualidade)",
    "Certificação Vegana (Vegan Society) em linhas selecionadas",
    "União pelo BioComércio Ético (UEBT)",
  ],
  faqs: [
    { q: "Quanto custa para se tornar Consultora Natura?",
      a: "O cadastro como Consultora Natura é 100% gratuito. Não há kit obrigatório, nem mensalidade, nem taxa de adesão. Basta se cadastrar pelo site da Natura ou com uma Consultora ativa." },
    { q: "Quanto a Consultora Natura ganha?",
      a: "A margem padrão é de 30% sobre o preço dos produtos (40% em datas especiais). Consultoras CND (digitais) ganham comissão adicional sobre vendas pela loja online. Líderes de rede recebem bônus progressivos de 1% a 3% sobre a equipe." },
    { q: "Quais são as linhas mais vendidas da Natura?",
      a: "Os carros-chefe são Ekos (sociobiodiversidade amazônica), Chronos (anti-idade), Tododia (cuidado diário), Kaiak (perfumaria), Mamãe e Bebê e a maquiagem Una." },
    { q: "A Natura é uma empresa segura ou pirâmide?",
      a: "A Natura é a maior empresa de cosméticos da América Latina, listada na B3 (NATU3) desde 2004, regulada pela CVM e pioneira mundial em sustentabilidade (B Corp). Não é pirâmide — é um modelo legítimo de venda direta por Consultoras, regulado pela ABEVD." },
    { q: "Em quantos países a Natura está presente?",
      a: "A Natura está presente em mais de 100 países, com operação direta em toda a América Latina, EUA e Europa, e expandida via marca Avon (também controlada pelo grupo) na maioria dos outros mercados." },
    { q: "O que é o Programa Amazônia da Natura?",
      a: "É o programa de uso sustentável de ativos da floresta amazônica em parceria com mais de 40 comunidades extrativistas. A Natura já investiu mais de R$ 2 bilhões na bioeconomia da Amazônia, mantendo mais de 2 milhões de hectares conservados." },
    { q: "Como funciona o ciclo de 21 dias da Natura?",
      a: "A Natura opera por ciclos de 21 dias (em vez de meses). A cada ciclo a Consultora faz um pedido novo, com novas ofertas, lançamentos e promoções. São aproximadamente 17 ciclos por ano." },
    { q: "Qual a diferença entre Consultora Natura e CND?",
      a: "A Consultora tradicional vende presencialmente com lucro de 30%. A CND (Consultora Natura Digital) tem além disso uma loja virtual personalizada e recebe comissão também sobre vendas feitas online via seu link." },
  ],
  founders: ["Luiz Seabra", "Guilherme Leal", "Pedro Passos"],
  foundingDate: "1969-01-01",
  foundingLocation: "São Paulo, Brasil",
  employees: 35000,
  alternateNames: ["Natura Cosméticos", "Natura &Co"],
  wikipediaUrl: "https://pt.wikipedia.org/wiki/Natura_%26_Co",
};

const Natura = () => <CompanyPremiumPage data={data} />;
export default Natura;
