import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Nu Skin",
  slug: "nu-skin",
  officialUrl: "https://www.nuskin.com/",
  domain: "nuskin.com",
  seoTitle: "Nu Skin: A Beauty Tech Mundial em Marketing Multinível | Ranking 2026",
  seoDescription:
    "Nu Skin é referência em beauty tech e MMN com US$ 1,7 bi de receita. Conheça LumiSpa, ageLOC, Pharmanex, plano binário Stairstep, países e a história da gigante de Utah.",
  rankingLabel: "TOP 20 MUNDIAL • BUSINESS FOR HOME 2026",
  heroHeadlineSuffix: "A Beauty Tech do Marketing Multinível",
  heroParagraph:
    "Fundada em 1984 em Provo, Utah, a Nu Skin Enterprises é referência mundial em beauty tech e bem-estar antienvelhecimento, com mais de 1 milhão de Brand Affiliates, operação em 50+ mercados e US$ 1,7 bilhão em receita anual.",
  heroBadges: [
    { label: "Listada na NYSE: NUS", icon: "check" },
    { label: "40+ anos", icon: "calendar" },
    { label: "50+ países", icon: "globe" },
    { label: "1 mi+ afiliados", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 20", hint: "Líder em beauty tech MMN" },
    { icon: "calendar", label: "Fundação", value: "1984", hint: "40+ anos de história" },
    { icon: "map", label: "País de Origem", value: "EUA 🇺🇸", hint: "Provo, Utah" },
    { icon: "globe", label: "Mercados", value: "50+", hint: "Operação em 5 continentes" },
    { icon: "users", label: "Brand Affiliates", value: "1 mi+", hint: "Distribuidores ativos" },
    { icon: "package", label: "Produtos no Portfólio", value: "200+", hint: "Skincare, suplementos e devices" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 1,7 bi", hint: "Fonte: Business For Home" },
    { icon: "factory", label: "Funcionários Globais", value: "4.700+", hint: "P&D, fábricas e operações" },
  ],
  aboutHtml: `
    <p>A <strong>Nu Skin Enterprises, Inc.</strong> é uma multinacional americana de beauty tech e bem-estar fundada em <strong>1984</strong> em Provo, Utah, por <em>Blake Roney, Sandie Tillotson e Steve Lund</em>. Listada na Bolsa de Nova York (<strong>NYSE: NUS</strong>) desde 1996, é uma das empresas mais antigas e respeitadas do setor de MMN globalmente.</p>
    <p>A <strong>Nu Skin</strong> ocupa o <strong>Top 20 mundial</strong> no ranking Business For Home 2026 com receita de <strong>US$ 1,7 bilhão anual</strong>. É reconhecida por inovação em <strong>devices de beleza</strong> (LumiSpa, ageLOC Boost, MyTRA) e na linha <strong>Pharmanex</strong> (suplementos com scanner de carotenoides patenteado, BioPhotonic Scanner).</p>
    <p>Mantém centro de P&D próprio com mais de <strong>75 cientistas</strong>, parceria com a <strong>Universidade Stanford</strong> em estudos genéticos antienvelhecimento e mais de <strong>110 patentes registradas</strong>. Líder do segmento "<strong>ageLOC</strong>", focado em ciência dos genes do envelhecimento.</p>
  `,
  milestones: [
    { year: "1984", title: "Fundação em Utah", text: "Blake Roney, Sandie Tillotson e Steve Lund fundam a Nu Skin em Provo, Utah, com a filosofia 'All of the good, none of the bad'." },
    { year: "1996", title: "IPO na NYSE", text: "Nu Skin abre capital na Bolsa de Nova York como NYSE: NUS, virando uma das primeiras MMNs listadas." },
    { year: "1998", title: "Aquisição da Pharmanex", text: "Compra da Pharmanex, linha de suplementos farmacêuticos com pesquisa científica." },
    { year: "2003", title: "BioPhotonic Scanner", text: "Lançamento do BioPhotonic Scanner, único scanner não-invasivo de antioxidantes do mundo." },
    { year: "2009", title: "Linha ageLOC", text: "Lançamento da linha ageLOC com tecnologia exclusiva baseada na ciência dos genes do envelhecimento." },
    { year: "2014", title: "LumiSpa", text: "Lançamento do icônico ageLOC LumiSpa, device de limpeza facial que revolucionaria a categoria." },
    { year: "2020", title: "Pivot para Beauty Tech", text: "Nu Skin se reposiciona como Beauty Tech Company, focada em devices e apps integrados." },
    { year: "2023", title: "MyTRA + Vera", text: "Lançamento da plataforma Vera com IA para personalização e do device MyTRA." },
    { year: "2026", title: "Top 20 Mundial", text: "Nu Skin mantém presença consolidada no Top 20 mundial Business For Home 2026 com US$ 1,7 bilhão em receita." },
  ],
  productLines: [
    { name: "ageLOC LumiSpa", tag: "Device de Limpeza Facial", color: "from-sky-500/15 to-sky-700/5",
      text: "O device de limpeza facial mais vendido da categoria. Combina vibração sônica patenteada com cabeçotes de silicone para limpar, exfoliar e estimular a pele em 2 minutos por dia.",
      items: ["LumiSpa iO", "Cabeçotes de Silicone", "Cleansers ageLOC", "App Nu Skin Vera"] },
    { name: "ageLOC Boost", tag: "Tratamento Multi-fase", color: "from-rose-500/15 to-rose-700/5",
      text: "Device com microcorrente para tonificar pele e definir contornos faciais, com gel ativador exclusivo.",
      items: ["Boost Device", "Activating Serum", "Booster Sérum"] },
    { name: "Linha ageLOC Skincare", tag: "Anti-idade Premium", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linha completa anti-idade com tecnologia ageLOC (genética dos genes do envelhecimento), incluindo Future Serum, Nutriol, Y-Span e o sistema Transformation.",
      items: ["Future Serum", "Y-Span", "Nutriol", "Transformation", "Galvanic Spa"] },
    { name: "Pharmanex", tag: "Suplementos Científicos", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Linha de suplementos com pesquisa científica e o exclusivo BioPhotonic Scanner para medir antioxidantes na pele.",
      items: ["LifePak", "ageLOC Y-Span Supplement", "BioPhotonic Scanner", "Tegreen 97", "g3"] },
    { name: "Epoch & Body Care", tag: "Cuidados Corporais", color: "from-amber-500/15 to-amber-700/5",
      text: "Linha Epoch inspirada em fórmulas etnobotânicas e linha completa de cuidados corporais.",
      items: ["Glacial Marine Mud", "Sole Solution", "Baobab Body Butter", "Polishing Bar"] },
    { name: "Nutricentials", tag: "Skincare Bioadaptive", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Linha de skincare bioadaptive com extratos naturais que se adaptam às necessidades da pele.",
      items: ["Celltrex CoQ10", "Cleansers", "Hidratantes", "Tônicos"] },
  ],
  planTitle: "Plano de Carreira Nu Skin — Velocity (híbrido)",
  planIntro:
    "Em 2021 a Nu Skin lançou o plano <strong>Velocity</strong>, um modelo híbrido que combina <strong>vendas pessoais + construção de equipe</strong> com bonificações simplificadas. É um dos planos mais modernos e amigáveis para iniciantes do setor.",
  planRanks: [
    { rank: "Brand Affiliate", payout: "Margem revenda", text: "Cadastro como Brand Affiliate com desconto e revenda." },
    { rank: "Brand Affiliate Qualificado", payout: "+ Comissões diretas", text: "Atinge volume mínimo mensal qualificado." },
    { rank: "Builder", payout: "+ Bônus Estrutural", text: "1-3 indicados qualificados." },
    { rank: "Senior Builder", payout: "+ Override 5%", text: "Equipe maior, primeira graduação de liderança." },
    { rank: "Executive", payout: "+ Bônus Executive", text: "Estrutura consolidada de equipe com leg breakouts." },
    { rank: "Gold Executive", payout: "+ Bônus Pool", text: "Recebe parte do pool global de receita." },
    { rank: "Lapis / Ruby / Emerald / Diamond", payout: "+ Bônus Crescentes", text: "Sequência de pedras preciosas como reconhecimento progressivo." },
    { rank: "Blue Diamond / Team Elite", payout: "Topo do Plano", text: "Patamar máximo da carreira Nu Skin, com viagens premium e bônus de seis dígitos." },
  ],
  pros: [
    "Empresa listada em bolsa (NYSE: NUS) com transparência financeira",
    "Pioneira em beauty tech com devices proprietários (LumiSpa, Boost)",
    "Forte investimento em ciência (Pharmanex + Stanford)",
    "Plano Velocity moderno e amigável para iniciantes",
    "Apps e plataforma digital robustos (Vera AI)",
    "Forte recompra mensal (subscription Cleansers, suplementos)",
  ],
  cons: [
    "Ticket inicial dos devices é alto (R$ 1.000+)",
    "Concentração de receita na Ásia (volatilidade cambial)",
    "Plano Velocity ainda em fase de adaptação em alguns mercados",
    "Concorrência crescente de devices de drugstore",
    "Operação no Brasil menor que em mercados maduros",
  ],
  countries: [
    "🇺🇸 EUA", "🇨🇦 Canadá", "🇲🇽 México", "🇧🇷 Brasil", "🇦🇷 Argentina", "🇨🇴 Colômbia",
    "🇨🇱 Chile", "🇵🇪 Peru", "🇬🇧 Reino Unido", "🇩🇪 Alemanha", "🇫🇷 França", "🇮🇹 Itália",
    "🇪🇸 Espanha", "🇵🇹 Portugal", "🇳🇱 Países Baixos", "🇧🇪 Bélgica", "🇸🇪 Suécia",
    "🇨🇳 China", "🇯🇵 Japão", "🇰🇷 Coreia do Sul", "🇹🇼 Taiwan", "🇭🇰 Hong Kong", "🇸🇬 Singapura",
    "🇲🇾 Malásia", "🇹🇭 Tailândia", "🇻🇳 Vietnã", "🇮🇩 Indonésia", "🇵🇭 Filipinas",
    "🇦🇺 Austrália", "🇳🇿 Nova Zelândia",
  ],
  awards: [
    "Top 20 Direct Selling News Global 100 — 2026",
    "Forbes Most Trustworthy Companies",
    "Edison Awards de Inovação (LumiSpa)",
    "Allure Best of Beauty (ageLOC)",
    "Force for Good Foundation — US$ 100 mi+ doados em projetos sociais",
    "Top Workplaces USA Today",
  ],
  certifications: [
    "GMP — Good Manufacturing Practices (Pharmanex)",
    "ISO 9001 / ISO 14001",
    "NSF Certified (linhas selecionadas)",
    "FDA Registered Cosmetic Facility",
    "Cruelty Free (linhas selecionadas)",
  ],
  faqs: [
    { q: "A Nu Skin é uma empresa séria?",
      a: "Sim. A Nu Skin é listada na Bolsa de Nova York (NYSE: NUS) desde 1996, com mais de 40 anos de história, presente em 50+ países e faturamento de US$ 1,7 bilhão. Regulada pela SEC e membro fundadora da Direct Selling Association (DSA)." },
    { q: "Quanto custa o LumiSpa da Nu Skin?",
      a: "O LumiSpa iO custa entre R$ 1.300 e R$ 1.800 no Brasil, incluindo um cabeçote inicial e um cleanser ageLOC. Há kits promocionais e descontos especiais para novos Brand Affiliates." },
    { q: "Como ser distribuidor Nu Skin?",
      a: "Para ser Brand Affiliate Nu Skin é necessário se cadastrar pelo site da empresa ou via convite de um afiliado. O kit inicial custa entre R$ 200 e R$ 500. O plano de carreira é o Velocity, lançado em 2021." },
    { q: "Quais os principais produtos da Nu Skin?",
      a: "Os carros-chefe são o device ageLOC LumiSpa (limpeza facial), o ageLOC Boost (microcorrente facial), a linha de skincare ageLOC (anti-idade) e a linha Pharmanex de suplementos com o BioPhotonic Scanner exclusivo." },
    { q: "Quanto fatura a Nu Skin?",
      a: "Em 2025 a Nu Skin faturou US$ 1,7 bilhão, ocupando o Top 20 mundial no ranking Business For Home 2026. Os maiores mercados são China, Coreia do Sul, EUA e Japão." },
    { q: "O que é o BioPhotonic Scanner?",
      a: "É um scanner não-invasivo patenteado pela Pharmanex que mede a quantidade de carotenoides (antioxidantes) na pele em segundos, indicando o status antioxidante do organismo. Único scanner do tipo no mundo aprovado clinicamente." },
    { q: "Nu Skin tem operação no Brasil?",
      a: "Sim. A Nu Skin opera no Brasil desde 2014 com sede em São Paulo, regulada pela ABEVD e com produtos registrados na ANVISA." },
  ],
  founders: ["Blake Roney", "Sandie Tillotson", "Steve Lund"],
  foundingDate: "1984-11-01",
  foundingLocation: "Provo, Utah, EUA",
  employees: 4700,
  alternateNames: ["Nu Skin Enterprises", "NSE"],
  wikipediaUrl: "https://en.wikipedia.org/wiki/Nu_Skin_Enterprises",
};

const NuSkin = () => <CompanyPremiumPage data={data} />;
export default NuSkin;
