import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Oriflame",
  slug: "oriflame",
  officialUrl: "https://corporate.oriflame.com/",
  domain: "oriflame.com",
  seoTitle: "Oriflame: A Beleza Sueca em Venda Direta | Marketing Multinível 2026",
  seoDescription:
    "Oriflame é a gigante sueca de cosméticos por venda direta, com US$ 1 bi de receita e operação em 60+ países. Conheça produtos naturais escandinavos, plano de carreira e história da Oriflame.",
  rankingLabel: "TOP 40 MUNDIAL • LÍDER EUROPEIA EM COSMÉTICOS MMN",
  heroHeadlineSuffix: "A Beleza Sueca por Venda Direta",
  heroParagraph:
    "Fundada em 1967 em Estocolmo, Suécia, a Oriflame é uma das maiores empresas de cosméticos por venda direta do mundo, com mais de 3 milhões de Consultores Independentes em 60+ países e US$ 1 bilhão em receita anual.",
  heroBadges: [
    { label: "Beleza Natural Sueca", icon: "check" },
    { label: "55+ anos", icon: "calendar" },
    { label: "60+ países", icon: "globe" },
    { label: "3 mi de consultores", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "Top 40", hint: "Líder europeia em cosméticos MMN" },
    { icon: "calendar", label: "Fundação", value: "1967", hint: "55+ anos de história" },
    { icon: "map", label: "País de Origem", value: "Suécia 🇸🇪", hint: "Estocolmo" },
    { icon: "globe", label: "Países & Territórios", value: "60+", hint: "Forte na Europa, Ásia e CIS" },
    { icon: "users", label: "Consultores", value: "3 mi+", hint: "Brand Partners ativos" },
    { icon: "package", label: "Produtos lançados/ano", value: "300+", hint: "Catálogo renovado a cada ciclo" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 1 bi", hint: "Fonte: Business For Home" },
    { icon: "leaf", label: "Filosofia", value: "Beauty by Sweden", hint: "Natural, sustentável, escandinava" },
  ],
  aboutHtml: `
    <p>A <strong>Oriflame Cosmetics AG</strong> é uma multinacional sueca de cosméticos fundada em <strong>1967</strong> pelos irmãos <em>Jonas e Robert af Jochnick</em> e <em>Bengt Hellsten</em> em Estocolmo. Com a filosofia <strong>"Beauty by Sweden"</strong>, é uma das maiores empresas de venda direta de cosméticos da Europa e do mundo.</p>
    <p>A <strong>Oriflame</strong> ocupa o <strong>Top 40 mundial</strong> no ranking Business For Home 2026, com receita de <strong>US$ 1 bilhão anual</strong>, presença em <strong>mais de 60 países</strong> e mais de <strong>3 milhões de Brand Partners</strong>. Tem forte concentração na Europa, CIS (ex-União Soviética), Ásia e América Latina.</p>
    <p>Famosa por <strong>fórmulas inspiradas na natureza escandinava</strong>, com ingredientes como mirtilo, lingonberry, ácido hialurônico vegano e tecnologia anti-idade própria. Mantém centro de P&D em Estocolmo, fábricas próprias e o conceito de <strong>catálogo mensal</strong> (17 ciclos por ano), com mais de <strong>300 novos lançamentos anuais</strong>.</p>
  `,
  milestones: [
    { year: "1967", title: "Fundação em Estocolmo", text: "Os irmãos af Jochnick fundam a Oriflame, levando cosméticos suecos diretamente aos consumidores via venda direta." },
    { year: "1970", title: "Expansão europeia", text: "Oriflame expande rapidamente para outros países nórdicos e europeus." },
    { year: "1982", title: "IPO na Bolsa de Londres", text: "Oriflame abre capital — primeira MMN europeia listada em bolsa." },
    { year: "1990", title: "Entrada na ex-URSS", text: "Após a queda do Muro de Berlim, Oriflame se torna uma das primeiras empresas ocidentais a operar em Rússia e CIS — virando líder absoluta na região." },
    { year: "2002", title: "Listagem em NASDAQ Stockholm", text: "Mudança para a NASDAQ Stockholm como uma das maiores empresas de cosméticos da Suécia." },
    { year: "2014", title: "Entrada em Wellness", text: "Lançamento da linha Wellness by Oriflame com suplementos nutricionais escandinavos." },
    { year: "2019", title: "Fechamento de capital", text: "Oriflame fecha capital após oferta dos fundadores, voltando a ser empresa privada familiar." },
    { year: "2024", title: "Reformulação Optimals & The One", text: "Relançamento das linhas-ícone Optimals (skincare diário) e The One (maquiagem premium)." },
    { year: "2026", title: "Top 40 Mundial", text: "Oriflame mantém posição Top 40 mundial Business For Home 2026 com US$ 1 bilhão em receita." },
  ],
  productLines: [
    { name: "NovAge", tag: "Anti-idade Premium", color: "from-rose-500/15 to-rose-700/5",
      text: "Linha anti-idade carro-chefe com 6 sistemas (NovAge Bright Sublime, Skinrunner, Ecollagen, Time Restore, Ultimate Lift, ProCeuticals), cada um para uma necessidade específica da pele.",
      items: ["NovAge Bright Sublime", "Ecollagen", "Skinrunner", "Time Restore", "ProCeuticals", "Ultimate Lift"] },
    { name: "The One", tag: "Maquiagem Premium", color: "from-fuchsia-500/15 to-fuchsia-700/5",
      text: "Linha de maquiagem profissional com bases, batons, máscaras de cílios premiadas e a icônica paleta The One Wonder Color.",
      items: ["The One IlluSkin Foundation", "Wonder Color Lipstick", "Wonder Lash 5-in-1", "Eyeliner Stylo", "BB Cream"] },
    { name: "Optimals & Love Nature", tag: "Skincare Diário", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Linha Optimals (skincare clássico para todas as idades) e Love Nature (vegano e natural com extratos botânicos suecos).",
      items: ["Optimals Even Out", "Optimals White", "Love Nature Tea Tree", "Love Nature Rose Water"] },
    { name: "Wellness by Oriflame", tag: "Nutrição Funcional", color: "from-amber-500/15 to-amber-700/5",
      text: "Linha sueca de suplementos premium com Natural Balance Shake, Omega 3, suplementos de cabelo, pele e unhas.",
      items: ["Natural Balance Shake", "Omega 3", "Hair & Nails", "Astaxanthin Plus", "Skin Beauty"] },
    { name: "Perfumaria", tag: "Fragrâncias Suecas", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Mais de 50 fragrâncias com perfumistas internacionais — entre elas Giordani Gold, Volare, Eclat, So Fever e Memoir.",
      items: ["Giordani Gold", "Volare", "Eclat", "So Fever", "Memoir", "Be the Legend"] },
    { name: "Body & Hair Care", tag: "Cuidados Pessoais", color: "from-sky-500/15 to-sky-700/5",
      text: "Linha completa de cuidados corporais, capilares, higiene oral e desodorantes, com fórmulas naturais.",
      items: ["Milk & Honey Gold", "Tender Care", "HairX Professional", "OptiFresh Toothpaste", "Activelle Desodorante"] },
  ],
  planTitle: "Plano de Sucesso Oriflame (Stairstep Breakaway)",
  planIntro:
    "A Oriflame opera com um plano <strong>multinível tradicional</strong>, com <strong>desconto de até 23% no consumo</strong>, comissão de até <strong>21% sobre as vendas pessoais</strong> e bônus de <strong>3% a 20% sobre a rede</strong>. Foco em recrutamento e construção de equipe.",
  planRanks: [
    { rank: "Brand Partner", payout: "23% lucro", text: "Cadastro gratuito como Brand Partner com desconto direto." },
    { rank: "Consultor 3%", payout: "3% override", text: "Atinge 200 BP (Bonus Points) no ciclo." },
    { rank: "Consultor 6-21%", payout: "6% a 21% override", text: "Escalada progressiva conforme volume mensal de equipe." },
    { rank: "Manager Group", payout: "+ Bônus Líder", text: "Atinge 12.000 BP em um ciclo." },
    { rank: "Senior Manager", payout: "+ Bônus Sapphire", text: "Forma novos managers em sua estrutura." },
    { rank: "Diretor", payout: "+ Diamond Pool", text: "Estrutura com diretores qualificados na rede." },
    { rank: "Gold / Sapphire / Diamond Director", payout: "Topo do Plano", text: "Patamares mais altos com participação em pools globais e viagens." },
  ],
  pros: [
    "Cadastro 100% gratuito como Brand Partner",
    "Marca europeia consolidada há 55+ anos",
    "Catálogo renovado a cada ciclo (17 lançamentos/ano)",
    "Forte tradição em skincare e perfumaria sueca",
    "Operação global em 60+ países",
    "Plataforma digital robusta com loja online personalizada",
  ],
  cons: [
    "Concorrência forte no Brasil (Natura, Boticário)",
    "Ciclos curtos exigem ritmo de vendas constante",
    "Plano tradicional, menos agressivo que binários",
    "Operação no Brasil menor que em mercados maduros (CIS, Ásia)",
    "Forte dependência cambial (produtos importados)",
  ],
  countries: [
    "🇸🇪 Suécia", "🇫🇮 Finlândia", "🇳🇴 Noruega", "🇩🇰 Dinamarca", "🇵🇱 Polônia", "🇨🇿 Tchéquia",
    "🇸🇰 Eslováquia", "🇭🇺 Hungria", "🇷🇴 Romênia", "🇧🇬 Bulgária", "🇬🇷 Grécia",
    "🇩🇪 Alemanha", "🇫🇷 França", "🇮🇹 Itália", "🇪🇸 Espanha", "🇵🇹 Portugal", "🇳🇱 Países Baixos",
    "🇷🇺 Rússia", "🇺🇦 Ucrânia", "🇧🇾 Belarus", "🇰🇿 Cazaquistão", "🇺🇿 Uzbequistão",
    "🇮🇳 Índia", "🇮🇩 Indonésia", "🇨🇳 China", "🇻🇳 Vietnã", "🇹🇭 Tailândia", "🇲🇾 Malásia",
    "🇲🇽 México", "🇧🇷 Brasil", "🇨🇴 Colômbia", "🇨🇱 Chile", "🇹🇷 Turquia", "🇪🇬 Egito",
  ],
  awards: [
    "Top 40 Direct Selling News Global 100 — 2026",
    "Marie Claire Prix d'Excellence de la Beauté (várias edições)",
    "Pure Beauty Awards (UK)",
    "Best Direct Selling Company in Russia",
    "Eco-Beauty Award (Optimals)",
    "Stevie Awards for Sales & Customer Service",
  ],
  certifications: [
    "Vegan Society (Love Nature, linhas selecionadas)",
    "Cruelty Free International",
    "ISO 9001 / ISO 14001",
    "Eco-Label Europeu",
    "Boas Práticas ANVISA (Brasil)",
  ],
  faqs: [
    { q: "A Oriflame é uma empresa séria?",
      a: "Sim. A Oriflame é uma multinacional sueca com mais de 55 anos, presente em 60+ países, com faturamento de US$ 1 bilhão anual. É membro do Sociedade Sueca de Venda Direta e da ABEVD no Brasil. Já foi listada em bolsa por mais de 30 anos." },
    { q: "Quanto custa para se cadastrar na Oriflame?",
      a: "O cadastro como Brand Partner Oriflame é 100% gratuito. Não há kit obrigatório nem taxa de adesão — apenas a opção de comprar o Kit de Início com produtos demonstrativos (entre R$ 100 e R$ 300)." },
    { q: "Quais os principais produtos da Oriflame?",
      a: "Os carros-chefe são a linha anti-idade NovAge, maquiagem The One, skincare diário Optimals e Love Nature (vegano), perfumaria Giordani Gold e a linha Wellness by Oriflame de suplementos premium suecos." },
    { q: "Como funciona o plano da Oriflame?",
      a: "É um plano stairstep clássico com desconto de 23% por compra direta, bônus de 3% a 21% sobre a rede conforme volume mensal e bônus adicionais nos níveis Manager e Director (até participação em pools globais)." },
    { q: "Em quais países a Oriflame opera?",
      a: "A Oriflame opera em mais de 60 países, com forte presença na Europa, CIS (Rússia, Ucrânia, Cazaquistão), Ásia (Índia, Indonésia, Vietnã) e expansão em América Latina." },
    { q: "A Oriflame testa em animais?",
      a: "Não. A Oriflame é certificada Cruelty Free International e várias linhas (como Love Nature) são certificadas Vegan Society." },
    { q: "A Oriflame está no Brasil?",
      a: "Sim. A Oriflame Brasil opera desde os anos 2000, com escritório em São Paulo, regulada pela ABEVD e com produtos registrados na ANVISA." },
  ],
  founders: ["Jonas af Jochnick", "Robert af Jochnick", "Bengt Hellsten"],
  foundingDate: "1967-03-01",
  foundingLocation: "Estocolmo, Suécia",
  employees: 5300,
  alternateNames: ["Oriflame Cosmetics", "Oriflame Holding AG"],
  wikipediaUrl: "https://en.wikipedia.org/wiki/Oriflame",
};

const Oriflame = () => <CompanyPremiumPage data={data} />;
export default Oriflame;
