import { CompanyPremiumPage, type CompanyPremiumData } from "@/components/CompanyPremiumPage";

const data: CompanyPremiumData = {
  name: "Primerica",
  slug: "primerica",
  officialUrl: "https://www.primerica.com/",
  domain: "primerica.com",
  seoTitle: "Primerica: A Maior Distribuidora Independente de Seguros de Vida dos EUA | 2026",
  seoDescription:
    "Primerica é a #8 do ranking mundial 2026 com US$ 2,9 bi de receita. Maior distribuidora independente de seguros de vida e produtos financeiros dos EUA. Conheça plano de carreira e história.",
  rankingLabel: "#8 RANKING MUNDIAL • BUSINESS FOR HOME 2026",
  heroHeadlineSuffix: "A Gigante dos Serviços Financeiros em Venda Direta",
  heroParagraph:
    "Fundada em 1977 em Duluth, Georgia, a Primerica é a maior distribuidora independente de seguros de vida e produtos financeiros dos Estados Unidos, com mais de 140 mil representantes licenciados, listada na NYSE: PRI e US$ 2,9 bilhões em receita anual.",
  heroBadges: [
    { label: "Listada na NYSE: PRI", icon: "check" },
    { label: "45+ anos", icon: "calendar" },
    { label: "EUA, Canadá, Porto Rico", icon: "globe" },
    { label: "140 mil licenciados", icon: "users" },
  ],
  stats: [
    { icon: "crown", label: "Ranking Mundial 2026", value: "#8", hint: "Maior MMN de serviços financeiros" },
    { icon: "calendar", label: "Fundação", value: "1977", hint: "45+ anos de história" },
    { icon: "map", label: "País de Origem", value: "EUA 🇺🇸", hint: "Duluth, Georgia" },
    { icon: "globe", label: "Mercados", value: "EUA, Canadá, PR", hint: "Forte concentração norte-americana" },
    { icon: "users", label: "Representantes Licenciados", value: "140 mil+", hint: "Agentes com licença de seguros" },
    { icon: "package", label: "Famílias Atendidas", value: "5,7 mi+", hint: "Clientes ativos" },
    { icon: "dollar", label: "Faturamento 2025", value: "US$ 2,9 bi", hint: "Fonte: Business For Home" },
    { icon: "shield", label: "Apólices em Vigor", value: "US$ 950 bi+", hint: "Valor de cobertura emitido" },
  ],
  aboutHtml: `
    <p>A <strong>Primerica, Inc.</strong> é uma multinacional americana de serviços financeiros fundada em <strong>1977</strong> por <em>Arthur L. Williams Jr.</em> em Duluth, Georgia. É a <strong>maior distribuidora independente de seguros de vida a termo dos Estados Unidos</strong>, operando também em Canadá e Porto Rico.</p>
    <p>Listada na <strong>Bolsa de Nova York (NYSE: PRI)</strong> desde 2010, a Primerica ocupa a posição <strong>#8 mundial</strong> no ranking Business For Home 2026 com receita de <strong>US$ 2,9 bilhões</strong>. Mantém mais de <strong>140 mil representantes licenciados</strong> que atendem mais de <strong>5,7 milhões de famílias</strong> com soluções de seguros, investimentos e poupança.</p>
    <p>Pioneira no conceito <strong>"Buy Term and Invest the Difference"</strong> (compre seguro a termo e invista a diferença), a Primerica é o único MMN focado 100% em <strong>educação financeira para famílias de classe média e baixa</strong>. Já pagou mais de <strong>US$ 22 bilhões em sinistros</strong> aos beneficiários desde sua fundação.</p>
  `,
  milestones: [
    { year: "1977", title: "Fundação por Art Williams", text: "Art Williams funda a A.L. Williams & Associates com a missão de revolucionar o mercado de seguros, defendendo o seguro a termo como melhor alternativa ao vitalício." },
    { year: "1989", title: "Aquisição pela Travelers", text: "A empresa é adquirida pela Travelers Corp., depois passa por Citigroup, e finalmente é renomeada Primerica." },
    { year: "2010", title: "IPO na NYSE", text: "Primerica abre capital na NYSE (PRI), separando-se do Citigroup e voltando a ser empresa independente." },
    { year: "2015", title: "Expansão de produtos", text: "Lançamento de novos produtos de poupança, investimento e proteção da renda além dos seguros de vida." },
    { year: "2020", title: "Plataforma digital", text: "Lançamento de plataforma 100% digital para representantes, com onboarding e venda remota." },
    { year: "2024", title: "Aquisição da e-TeleQuote", text: "Compra da e-TeleQuote, plataforma de comparação de seguros Medicare, expandindo portfólio." },
    { year: "2026", title: "#8 Mundial", text: "Primerica mantém posição #8 no ranking Business For Home 2026 com US$ 2,9 bilhões em receita e mais de US$ 22 bilhões pagos em sinistros." },
  ],
  productLines: [
    { name: "Term Life Insurance", tag: "Seguro de Vida a Termo", color: "from-sky-500/15 to-sky-700/5",
      text: "Carro-chefe absoluto. Seguros de vida a termo (10, 15, 20, 25, 30 e 35 anos) com prêmios fixos, valores de cobertura de até US$ 5 milhões. Filosofia 'Buy Term, Invest the Difference'.",
      items: ["Term 10/15/20/25/30/35", "Increasing Benefit Rider", "Child Rider", "Waiver of Premium", "Terminal Illness Benefit"] },
    { name: "Investimentos & Aposentadoria", tag: "Mutual Funds & IRAs", color: "from-emerald-500/15 to-emerald-700/5",
      text: "Plataforma de investimentos com fundos mútuos (mutual funds), IRAs, 401(k), planos de aposentadoria e Roth IRA — em parceria com gestoras como American Funds, Invesco e Franklin Templeton.",
      items: ["Roth IRA", "Traditional IRA", "401(k) Rollover", "529 College Savings", "Mutual Funds"] },
    { name: "Annuities & Long-Term Care", tag: "Anuidades e Cuidados", color: "from-amber-500/15 to-amber-700/5",
      text: "Anuidades fixas e variáveis para garantir renda na aposentadoria, e seguros de Long-Term Care (cuidados de longa duração).",
      items: ["Fixed Annuities", "Variable Annuities", "Indexed Annuities", "Long-Term Care Insurance"] },
    { name: "Debt Solutions", tag: "Solução de Dívidas", color: "from-rose-500/15 to-rose-700/5",
      text: "Programa exclusivo de consolidação de dívidas e refinanciamento, com plano personalizado para sair do endividamento.",
      items: ["Debt Resolution", "Mortgage Refinance", "Home Loan", "Auto Loan"] },
    { name: "Pre-Paid Legal & ID Theft", tag: "Serviços Jurídicos", color: "from-indigo-500/15 to-indigo-700/5",
      text: "Acesso a planos jurídicos pré-pagos e proteção contra roubo de identidade, em parceria com LegalShield.",
      items: ["LegalShield Plans", "ID Shield", "Small Business Plan"] },
  ],
  planTitle: "Plano de Carreira Primerica",
  planIntro:
    "A Primerica opera um modelo único de <strong>representantes licenciados</strong> com plano de carreira em <strong>5 níveis baseados em performance e desenvolvimento de equipe</strong>. Comissões variam de <strong>25% a 95% da primeira anualidade</strong> dos seguros vendidos.",
  planRanks: [
    { rank: "Representative", payout: "25% comissão", text: "Início após pré-licenciamento. Comissões diretas sobre vendas pessoais." },
    { rank: "Senior Rep", payout: "35-45% comissão", text: "Após obtenção da licença completa de seguros de vida e produtos." },
    { rank: "District Leader", payout: "+ Override 3-10%", text: "Formação de equipe direta com pelo menos 3 representantes licenciados." },
    { rank: "Division Leader", payout: "+ Override 15%", text: "Estrutura de equipe consolidada com sub-líderes." },
    { rank: "Regional Leader", payout: "+ Override 25%", text: "Múltiplas divisões qualificadas na estrutura." },
    { rank: "RVP - Regional Vice President", payout: "+ Override 50-95%", text: "Patamar de liderança regional, com bônus de produção e participação em pools." },
    { rank: "SNSD - Senior National Sales Director", payout: "Topo do Plano", text: "Topo absoluto da carreira Primerica, com ganhos de seis e sete dígitos anuais." },
  ],
  pros: [
    "Empresa listada na NYSE (PRI) com transparência total",
    "Único MMN focado 100% em serviços financeiros",
    "Treinamento e licenciamento profissional completos",
    "Comissões altas (até 95% da 1ª anualidade)",
    "Mercado enorme nos EUA (75% das famílias subseguradas)",
    "Pagou mais de US$ 22 bi em sinistros (credibilidade comprovada)",
  ],
  cons: [
    "Operação restrita a EUA, Canadá e Porto Rico",
    "Necessário obter licença de seguros (exame estadual)",
    "Custo de licenciamento e renovações anuais",
    "Não tem produtos físicos (sem revenda de consumíveis)",
    "Compliance regulatório rigoroso (mercado financeiro)",
  ],
  countries: ["🇺🇸 EUA", "🇨🇦 Canadá", "🇵🇷 Porto Rico"],
  awards: [
    "#8 Direct Selling News Global 100 — 2026",
    "Fortune Most Innovative Companies",
    "Forbes Best Mid-Size Employers",
    "Maior emissora de seguro de vida a termo dos EUA (LIMRA)",
    "Stevie Awards for Sales & Customer Service",
    "Black Enterprise Top 50 Companies for Diversity",
  ],
  certifications: [
    "FINRA Member Firm",
    "SEC Registered Investment Advisor",
    "NAIC State Licensed",
    "Better Business Bureau A+",
    "AM Best A+ Financial Strength",
  ],
  faqs: [
    { q: "A Primerica é uma empresa séria?",
      a: "Sim. A Primerica é listada na NYSE (PRI) desde 2010, regulada por FINRA, SEC, NAIC e autoridades estaduais americanas. Tem mais de 45 anos de história, US$ 2,9 bilhões em receita anual e já pagou mais de US$ 22 bilhões em sinistros aos beneficiários." },
    { q: "O que a Primerica vende?",
      a: "A Primerica é especializada em produtos financeiros: seguros de vida a termo (carro-chefe), fundos mútuos (mutual funds), IRAs, 401(k), anuidades, planos de aposentadoria, solução de dívidas e serviços jurídicos pré-pagos (LegalShield)." },
    { q: "Como ser representante Primerica?",
      a: "É necessário passar por pré-licenciamento da Primerica, depois obter a licença estadual de seguros de vida e produtos. O custo inicial gira em torno de US$ 99 + taxas estaduais. Após licenciado, o representante ganha entre 25% e 95% da primeira anualidade dos seguros vendidos, mais comissões recorrentes." },
    { q: "A Primerica está disponível no Brasil?",
      a: "Não. A Primerica opera oficialmente apenas em EUA, Canadá e Porto Rico, sem operação no Brasil ou na América Latina." },
    { q: "Qual a diferença entre Primerica e outros MMNs?",
      a: "A Primerica é o único MMN listado em bolsa focado 100% em serviços financeiros. Tem licenciamento profissional obrigatório, não vende produtos físicos e atua em um mercado regulado (FINRA, SEC), o que dá enorme credibilidade." },
    { q: "Quanto fatura a Primerica?",
      a: "Em 2025 a Primerica faturou US$ 2,9 bilhões, ocupando a posição #8 no ranking mundial Business For Home 2026." },
    { q: "Quanto a Primerica já pagou em sinistros?",
      a: "Desde 1977, a Primerica já pagou mais de US$ 22 bilhões em sinistros aos beneficiários de apólices de seguros de vida, com mais de US$ 950 bilhões em apólices em vigor." },
  ],
  founders: ["Arthur L. Williams Jr."],
  foundingDate: "1977-01-01",
  foundingLocation: "Duluth, Georgia, EUA",
  employees: 2700,
  alternateNames: ["Primerica Inc.", "PRI"],
  wikipediaUrl: "https://en.wikipedia.org/wiki/Primerica",
};

const Primerica = () => <CompanyPremiumPage data={data} />;
export default Primerica;
