// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxwaowrxmzpnvoqkzqfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4d2Fvd3J4bXpwbnZvcWt6cWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDU0MTUsImV4cCI6MjA3NDM4MTQxNX0.PG4J9eBDgAnAlygWDuM3S4gMcMIbXjF3_PcOaeVUjh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if we're in a browser environment
const isBrowser = typeof window !== 'undefined';

// Safe storage for SSG - only use localStorage on client side
const safeStorage = isBrowser ? window.localStorage : undefined;

// Create a conditional client that works for both SSG and client-side
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  }
});